---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: alloy-syslog
  namespace: alloy
spec:
  ingressClassName: traefik-external
  entryPoints:
    - syslog
  routes:
    - services:
        - name: alloy-syslog
          namespace: alloy
          port: 514
          nativeLB: true
