---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: alloy-syslog
  namespace: alloy
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - syslog
  routes:
    - services:
        - name: alloy-syslog
          namespace: alloy
          port: 514
          nativeLB: true
