apiVersion: v1
kind: Service
metadata:
  name: alloy-syslog
  namespace: alloy
spec:
  type: ClusterIP
  selector:
    app: alloy
  ports:
    - name: alloy-syslog
      protocol: TCP
      port: 514
      targetPort: 514
