---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nebula-sync-secret
  namespace: nebula-sync
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: nebula-sync-secret     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: PRIMARY            # key in the Kubernetes Secret
      remoteRef:
        key: nebula-sync-secret/PRIMARY
    - secretKey: REPLICAS            # key in the Kubernetes Secret
      remoteRef:
        key: nebula-sync-secret/REPLICAS
