---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nebula-sync-secret
  namespace: nebula-sync
spec:
  encryptedData:
    PRIMARY: AgADE8GEJNgPkmfX79pbJ+RnZcdf3ZLST67bO6MAnr4289zTBYZg8Y/i1NqACFaL4HTnnaH0fT9qBpyWjTRQIcmf12JpSnjQfcYfmhwEnNmY/ncOcbe6UfL0IzE8+OYIhBB+ljJpIZ2Hb83wRFnn2P5iGUdCyQT5PAVeAVth5MXkuLx5pR4UTP8cq+0x6ptwkW7O1JA6GfD2bfnaPzgOZXVeR1hpJli2yeNZhaYMoj8LqriPZ6c/d90hdOZeDEaG2HlBOWPxpAPZj0FbJ7+VVAjrznm+P4fHN+Dp22qwfRFJr9HuoVyG+bbwfR3/MSXO7f8TJqKJJREkshmjHfWcB0BGN2en4gbmO3DE/VE2JA5aWWUgG/1KkYkoCAxrQXvbd6x18h0JTmt8LWaYQFr9sAriLpEy7SW9jrX3GkCe8qtRBx7QQbwjdExIkBvuykjvBWYzp7i7S3dCymCujtEc4v1bYbbRVusFEwzR38ZAtOBZX3eNVmxXiCvrLnbWAWKZpScC7DwCaExQR9ls9HfxXkeZMVBCxAMhUQkfyz51BZZwEo50oYY6vft5zM3Bjm2eDrCgrhWVPnbI4OW3trEVSwi9AUUR7cnzjAmzVZU0Z/N6XLWpwiR5cdlwyiQHmHyLkfQxCw4LiMf727UQMxs7ESI3gATGcZeBG7BI4wTcgIZX+lsTNF1qYCgI7zR3q6R1vyFkBlqnuHT33DfyuHWa4VQjt29DJdRfxC9lcFln3T9b0lWeWySgcADIFmTz9uiGu3xd0GTjdfVsfQO1PTyVwZi4EiOMCe1t3QLt/Vsx3KJ8OSyB0w==
    REPLICAS: AgBfbsEFryCWhTlNKb1m+hYuxMrkH3B75VuHaEkRI9TFADhHFUVaNGt9N0N7N04wjY0h2bHcgRp/1lJxPsdKCzwoc16MmIyubPYul4L3ZVdrcigYlnZtUqoca0lDHLa9Tbbsw/tehxpkQjeTU6zgtapVIDmnRa9dhKC/Ej9dF5x2FrFjq4rUmhZ7CvJgCD/x29wtREYymn3W2jv9gWGe8RaUrGCv1I2QdyPqzOhvnM315RsdXprrhAC7djak1LuD2k4gxlLKqrimS4UR5t8Iszz6rG9gzg9k+657aTlNoAPYtrWPAGvL/cPWrh8EzEfM5FPXj2NFWhoJi4J+B8nhoVD+Q+RgIdnhZVsAOHRwfQssl4dpcRy4h3DKNaFhaROeHvLAnrZcy+MXAEitSOy9vhtbnUq7D6ou/oYLDgmkHSouszZDujgQi3cMgRY/AjgS2Ss4fq9hMmGsVCoyXifDbwTLv8NQG8pGJ/6OCHMLnv6vGPxP1QE1G6q+iGmOgS0Y62MDWMpIIj8VbevTUI1SXhHcpe6/asqxhMo8LspIwYFi3Bu7Vagv504iqqdU7gRS2Qoyj9vy3DW9Gr2STZ9uOYdBT30nWs/vePjfsfRgtNSNz6nZjpZY/xnyHg0dpHyeCDS3uP1zD0qHbWA3AEOvTPVcFOXqR/mbhLKurRJKAtUMKrWF8MQKVYHOpZBcDKx6r1t0v3ajPmg2NvSxc24Oayl2wOqvJYXxDdDyk/eAxDYTq6/25yEXu0+jkI9aX7mw+BFjzsA/pj9+psWY/aWb8WY=
  template:
    metadata:
      creationTimestamp: null
      name: nebula-sync-secret
      namespace: nebula-sync
