---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nebula-sync-secret
  namespace: nebula-sync
spec:
  encryptedData:
    PRIMARY: AgBh+448WodXZ26/EnFGJnXSogsaogCfs7OM3OMT/18mPTpFCHekf4H/EAO8G8i/jCPL+XMqqfa9VSczcyNNz8mfB6Z/dViNDDR7VV3+kSsOZao8ggx4i0lU74Ptl3m3HObRBoRIUZWOAZo4TPA8stx+Z8AlSSCIVU95vUpi5y9gL2WFDtvkUyxFJb/0J+0xCiKaTCfoI+UwAUlBhX8gYCqOPh21ozFEeeksLlH85wmbvs/etCkDsViHRYkId16RpjNAvC+a4BS378nMRsgP76bRR8BU55vYFk1i7Bsv+HLzMB+QF9z1BW3+UgOjPE/2dOrZXNGU9wkvICCs3xEEuCjO3nrAoPZ16Il/vxTiBvVa/rv8jqSfbgMgnfHXEbNJ9NauG8r/swwZqqMIQ+rNbER0pUq+tj5zidUqGUrMT8TyGU7xV0rGOvwaZmGk7qKweorfgGF6j4I66kNFCu1+vJ0r4kik8uLwsudV3h+rg6TQHnuBqONaJXlhzwAXmsm8v+gyOr+Dx2aHHGOeLW3Ztod/miS6V7N9wJUSVVXkCqOYtKlr04TjkZ7z5IDmSMKoj7S/Ef8Vp3wLQppQcgUZS0zN+bmTwYhpB1IiPra1nfP15xwY/icHrt5BSmQV05A9RU/r56bTHECLS29H+CUFAfPAlQgxjXEI5JUxU/fMXN532AUt3KlIIvo2TiGjKchLiYuymQmeb5XQrlXzGcWsE9n1c6h2cq5yd7B9bxEuLwwSdxf2b8KXUf5pPB68xnLDzupKJGGrD0o+f8rqqbyCzFz9k6FmudrGSaLFYdnrNhSdcWv8KGk=
    REPLICAS: AgCHQTac5QBkzsm/r59AXewmRfTxpCcRS1DP68oQ+1eZm9BAZn+Oudv0RRyJV4aBu1MI0g0UQW3nOyRUmaZkETdE9AG0LoL/B267IQa/w7lDyL4W4jpEyBkCVSpwzfJQazMpgb0x9nDiUXldarCtl0DC35mjWTEniHBmiNsqXYxV6/zQOCtLkZm9Zyv1BmQEhOtvdbHO30CrXDybegZF8XZ5pAzvNEl3F3BJRXFjGlctiPxMzEbZJFWiTZUxhY0w103GAIFb3+w3eaGCt0mx6tNqjWB6qs579dqTz69UwFIFP2GTxT5DHt7DmuYycVtQPm5ONmH/NeHzS+1qlp501jkdD/0EfgrZbaXxrS5m99Nw5r+2PTiqcZmjoajvezYtGs4TmUlLQ7w/BuAC5h8SAwzscJFT0th3ymBtN2FNOKcQkgrrstcIaezG1ni1VlrcGTMVtNqG0ozh60jYpXYi7HxUQYKLnmYWpBGsdlVvUoZ7dI2eb5VozCMC112Jj4/JBFxrHpt2eSDfg2J1xk2a3UWtrs4UNw6XPIlHzh2Uuea03+FtDzSSyChVWqPoRawuyuRuYEzu0Ed8OpMcHzahDTQz7xI/dOIIfke35r61jBODp2P9USH91XRFHLKtFf1QbqWIBJtXI3Hcss9cDi8iWyn3BRDvOzJ110D6Z9s19q3qvehyCZaZz0SYYo/PM2OmjLyZjeucNuJ1IWm26g+AYzKPZMy0HMY66tvdzzszHT/Gh1nHF0v3FPNs82RGCscdt6LN5B1NQhrwcjj/BGhpFvQ=
  template:
    metadata:
      creationTimestamp: null
      name: nebula-sync-secret
      namespace: nebula-sync
