---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nebula-sync-secret
  namespace: nebula-sync
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: nebula-sync-secret     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        PRIMARY: http://pihole-web.pihole.svc.cluster.local|{{ .primary_token }}
        REPLICAS: https://10.10.50.5|{{ .replica1_token }}
  data:
    - secretKey: primary_token            # key in the Kubernetes Secret
      remoteRef:
        key: nebula-sync-secret
        property: nebula-primary-token  # 1Password item name
    - secretKey: replica1_token            # key in the Kubernetes Secret
      remoteRef:
        key: nebula-sync-secret
        property: nebula-replica1-token  # 1Password item name
