---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-database.yaml
  - cake-pricing-postgres-secret.yaml
  - cake-pricing-intake-secret.yaml
  - cake-pricing-calendar-secret.yaml
  - cake-pricing-smtp-secret.yaml
  - migrate-job.yaml
  - price-sync-cronjob.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - servicemonitor.yaml
  - prometheus-alarms.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cake-pricing
      app.kubernetes.io/part-of: cake-pricing
      app.kubernetes.io/instance: cake-pricing
      app.kubernetes.io/component: cake-pricing
    includeSelectors: false
