---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.apprise: "default"
    notifications.argoproj.io/subscribe.on-sync-failed.apprise: "default"
    notifications.argoproj.io/subscribe.on-health-degraded.apprise: "default"
spec:
  description: Default project, allows all sources and destinations
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
