---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default
  namespace: argocd
spec:
  description: Default project, allows all sources and destinations
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
    - group: discovery.k8s.io
      kind: EndpointSlice
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
