---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-credentials
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: argocd-credentials     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
    - secretKey: redis-username            # key in the Kubernetes Secret
      remoteRef:
        key: argocd-credentials
        property: redis-username
    - secretKey: redis-password               # key in the Kubernetes Secret
      remoteRef:
        key: argocd-credentials
        property: redis-password
    - secretKey: oidc.authentik.clientSecret                 # key in the Kubernetes Secret
      remoteRef:
        key: argocd-credentials
        property: oidc.authentik.clientSecret
