apiVersion: v1
kind: Secret
metadata:
  name: bitnami-oci
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: bitnami-oci
  url: registry-1.docker.io
  enableOCI: "true"
  type: helm
