---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-oci
  namespace: argocd
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: argocd-github-oci     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: username            # key in the Kubernetes Secret
      remoteRef:
        key: argocd-github-oci/username
    - secretKey: password               # key in the Kubernetes Secret
      remoteRef:
        key: argocd-github-oci/password
    - secretKey: name                 # key in the Kubernetes Secret
      remoteRef:
        key: argocd-github-oci/name
    - secretKey: url                 # key in the Kubernetes Secret
      remoteRef:
        key: argocd-github-oci/url
    - secretKey: enableOCI                 # key in the Kubernetes Secret
      remoteRef:
        key: argocd-github-oci/enableOCI
    - secretKey: type                 # key in the Kubernetes Secret
      remoteRef:
        key: argocd-github-oci/type
