---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-github-repo
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: argocd-github-repo     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
  data:
    - secretKey: username            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-github-repo
        metadataPolicy: None
        property: username
    - secretKey: password               # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-github-repo
        metadataPolicy: None
        property: password
    - secretKey: name                 # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-github-repo
        metadataPolicy: None
        property: name
    - secretKey: url                 # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-github-repo
        metadataPolicy: None
        property: url
    - secretKey: project                 # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-github-repo
        metadataPolicy: None
        property: project
    - secretKey: type                 # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: argocd-github-repo
        metadataPolicy: None
        property: type
