---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCCZue2sxZlcSbw/UMKGW8DLnEJg/p9eUljhRCM7HWzbt6iPJvaCZUYHd4LtVIJ/dTZfAxjRGzjQvqWB75N7uMUyQMuMG+txD1h5N8UwjKUWM6N61MLU2dWhE3To07SfB+VvfvJ+EVzyLWXYFsHBj9EqYJq2CVSdVpa3TxMC2kOsbUtr6i9dN+4F5TDJIj5u5sVkyI4tqe8xNK8stvmm1kuSUn78/d85xCK4EFSdilsPV/lAnEQxeKBiU6k7/cgQGDWK5wYDhk4AG/uSz5ArhS1YuFKj5onD0qQPw912e8uwzgcvTb7IO6qN6gBktlypqOj2BT+YzP3/MZrKuHO2J0hYPTTtSEH2q2j1/zWKNoTv3V7yztetPNrL6BbYDL+3JU7pTzc+9rTDkpwaGCjHJYIsBE5iEGKTZwf74oMEdBJBvs/Ky0vFOIUWZtPwmD5YONdfIGa2SlhnNRYzrgSRVb9nwsgJsxBSKffvFqSIyEuPUqrLEdRQ1zcipUUpYGYqDviCG1wjG1Yw9NW2/8C1epXrauox1qvXbT8nqfiPeAdLOEvrZ4X9mEsXqzVyJcj5FMSwf6rebywx5LWtZtTpkyhaFwrfXf8r4Ck4xMOB2ECiefGV3bSOF5F3gHNzvtvpmjVC+TsqaifFRnL8+9LdKrJji/f2OAJM0dbQbmjTLExDpYd+cJ8GfkyveYY8gSt4P4OGh4g/LFZWBkVoaAoIRKy3CEmDCDma2eBnazg2te/bQUK2mrP7Vor
  template:
    metadata:
      creationTimestamp: null
      name: redis-password
      namespace: redis
    type: Opaque
