---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-acl-users
  namespace: redis
spec:
  encryptedData:
    users.acl: AgB4hxxSdXNzS+LZZXKiujDbp9ela42S7w0JI1D38HqjlyFqflcbODjKr2ODV9ThA7Fxb08vaQ590fjsu0Ypyx1znnhf3Qdsc3LggVL2ibTvkHXDUsh0custf56AMctmFGHpbGkm7z5awjX/LsSgplTrPIV/Ya4aGwZMWRx1N856q0EX0Sxl75GUmeUcOEkgBwYGUDUU1ErAOEBV87rsy0kqgGRMDQOVhb+rnL0IaLGxsxasYZOm6QpRWwJkOGZUDwqSz9SiBDHhygz0n7w95mSsbgukH8si8uHqHFIstEVNb1hk2J6ZrhR/1wMWY126fi2eHkNb3DZCTgY01bhchuoG1sZmQSLF9EIQAaRtHHqjTH5wNk84DDRkItvlPBu4ImOyygKwT9Y4jTQHUWVk0raIUbHAlFrjfDY7n5bnMjXR+am+mGRy+r5M9Gk8R7CD2VwUgiRD5zxXve+wvi3Z9UD+MjFyXNa5fIxZysaKrTcCuVt51w5B8jjUAhjtfNTlo4doR6+ieM2IQLmQK70XczlOoQzXJng+zCo7fQSe+U2TQ6AAEuVskdPo/b9HTH3FUFz0MKBQZtsVCsgiEHJ8sH7cjj4H1+dhe+RZVjqaLYJxzFWqMZSjSVr9Xz0feWJJJwGMJhIdFy28r81bB5GaPq6Dl/zr+IXJ7WGQgKiSThucQZn9ngQpDgRcpnDEXjCC+7EWOnUPuI9uFz37++4BRsafZhVFN8zu+L14N1eR4qIMYwbHpbMq6SFo4sxiNJB2rT+jMidjl18UQq1dIE3X52b3X3vmLrEy6fQUkFAjg74aF2Y/6Pk2XGh6T+gRmpIShHWsQFjXLnnt0F+jtmSa87TQcRJwQeqyFcNnAcE0jDjXV5fx5LNnaReFT+zrwfm4JblNhUf5Rxjw82kmvs2GJw5aTANycAxQ0y8x/E6j1rzAd7FvRVg7CZFByb6R0MpZEM5+wFThz8ZarQObXuOqvC8W5TWWdi8umdno+hcdWHgCzCMG8lTKMbrFGh0vvzYYZjuKbP8NCSvb/whL0wI+uahqR34395SjKVghkeZIITtZBM8kBF3HLaSdRpiby7JH9yxkpSX6+mzLtH2yKhwnW+3SX2BrLNdsmjUv1VvJPlZRYzvYNpotN28PvZFOJ2XCZVh+QX7WnmiBvUb+qT3xVIxgdzuovz3kD/idWTdORuBYw3bJycOacLBoX4jjwGkB5XsqzVupMMCNBgaAf1tPmAv1fjqEE29gYfz5s+WV0/w5bW/DFJOnYiiQPRgKtpW6EOd24+kYDTB4bE5RmYpJxSCmhaWLTeIX+ubh
  template:
    metadata:
      creationTimestamp: null
      name: redis-acl-users
      namespace: redis
    type: Opaque
