---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-acl-users
  namespace: redis
spec:
  encryptedData:
    users.acl: AgBUaKeubn0Ahu6rQ8ssXKrkjo+Ejnr/LC2YEZx2R8EUZ/H4KS6sluEfCa30ncyr7KdTdvpy60cG9o9X49eQdzwbBkLOM5iy1OeJytrZVGJaLV+Gw2UzkWZ7eqGUFRtzD/fCXhsLk5oj6Cp2JXRYEL3dFqmhoigCwD/QkkIQdRWA8z6tE84Ekja0t5Hyu3x7dSxiuygD6UcGE+64aEJkhWQ0/VZbFMYHcWWAoTluZ7V5oXQZhSMdmweMGIVIePg0YjCyDnMb/8NBKMzR6CmkW4DwZZhpReOoXYYTTupTr8whUSR7xuVQGWJ9v/KKjZo1KErhn+QryzMYnNvlHbAyw/LrBeq+OStJ1h1ZBcCr/2mm7w5WAsrHyLABKXI/Oz9nAQc6WB5JW97qBPLrCL7IAriNJBg7bP6uoFxge6+u0bGWfS7yiiu2eQvgvEMhNSYnEwIGLWWMjHSqn9LNwHyouQeEua9aFIDnyac+7o/0rM8IMzR3NBSOS0mlCjxJDWFiSXsuT6OxE9f2dwkpCyKSS7t4O/QhdVWkuQ4xtaVXkB6VmmG1yTseyM3qFNs8SfbljTPSkFcNqdVZMnccc8WsttAP0RARGK93cSFk6THn94FPa1496bMFyohMlGf64FPeef5haJFFXzwBWZUXJSQ69aWiPZrQgSn1NK1ptyhi+gW6f3looT5WqapVjyxwyrMjnNaxSvIVoFtk1SVXzma/s1UCYTjgGMPO7mcgSVDc/+ohnzZJFTACQB+94HscgOMORCotk6Vnviglunjgc28uJ0ZyRYBI3H0PqcceU5e8rjcetF5KeLdRDEl9p0lQXwxXvG6kHLz3r/7rmdKW46OAzEQzVpQBR5kk0ampd8FFyo5nPvE2DAQZCqjeFGw2CreSsOfvKYGdGzGyikZS0CMkww7LG9X8Rm7C2qrftiXGpZR4L8P4HHH7VElO9rGGHuKEvp5Fo3Iyz/cDh3xFMqBwweTGom5UH4ZQAzh3dhJzcvjTl3yw7O/jX2acyStoFxEBGL7b7gcpx4DD1mGJoIa+kJWlhWoycUc+uo1K6KtUotJdr8xzRze6iNIJdHEX25TWMgttV34E638R/wic4wwXZ+jbfDBjC7nSr5gXmmLwgLi6uCJrvjlZDvGlYqy2zQSN2DkLarUKvMzir0Dj7qJSva11/IF0Hmqp5AIip4T7ghOGZYrCEcfm91jUyHVarORLazoODjXuCQzrfUi2KX17VOLXzT+tG82VP6X3LEHeTPsix1qIDtsPRFW+CUDkKPecn4WB4DIKOV4t9i9Sng9heEzoV18iw2/pQVtVoVxCqALvZYfypxGTv9AUFG73HG/F3GD56I+vHnd97iAD3H7e6rG7pU7ZYvQSOCUifJypD0JqQqV3hXFEGkYo3ZKZTsnrUMt5IC3aMNWV+zdIS3b4P5I0
  template:
    metadata:
      creationTimestamp: null
      name: redis-acl-users
      namespace: redis
    type: Opaque
