---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secrets
  namespace: redis
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: redis-secrets     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: redis-username            # key in the Kubernetes Secret
      remoteRef:
        key: redis-secrets/redis-username
    - secretKey: redis-password            # key in the Kubernetes Secret
      remoteRef:
        key: redis-secrets/redis-password
    - secretKey: users.acl          # key in the Kubernetes Secret
      remoteRef:
        key: redis-secrets/users.acl
