---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    redis-password: AgCKF89suSZDVQKOTS/DLUQMTTf1u3XmrHtq1sknTP8jIARp0SRxwyp36Mg9/TyJO5Nsw9PO/9nuvfE+TDHhYLNutI/rlNal7/dwvIm9wh/7G5QtKa5fUT9KV7861QCshGO/NV2OTj9CtEYgzZw/LI456YXH2gJGnMIXtRfdcWijf7aDg66Nl3cJbhQT2+8XNzeZgBUQctga2WK3mQyWsVkyJw2HdqWznSwfW+fst7sJgcTOHh5WXcgz9MfWtKkaajh8r+Twcg/yRF9kclUyTh++0KTLLg7Ul6c2W639tplPB3MCkDfTSC9p+866A2+tlWUDz8GGUQdM6k9qMiMcC2lsCSYJKXImZZi/I+gr8R429Gi5NcrAUEP4p3B5MAtb4c/YzspRa5JJ2dqKaWgNnKl+15XWmMPVIDUv66kayFmVMZPbD3jF3LXKYWeiwYLJvPyH7bhQAeor1l5Ci+0gOWoqnapXiJfBvhNb+kZXxapO8qv4CPgPk6HZitCYY+D25Fl2SM/35J876L25Do6WaXbFOwI6EqRkRsCoOhRUPpxM81FwO/5Q3OBgrBMB4PB0Zq6WUUz+SaSc/5krxzZaRGO+TyDsA0ijzqGUYJxLClgTmKjuG2SASFG0WEyAHQZiTB1vKcM9sf+2GA9dTnir0l5HeSYJZiPkkC2cxHNfMyQHPbfCA25BJmh7XPIGGyITfZDlWbhvmfJtqXKha+OHm7uVuZ6nENJHnx35SsVnoz5BCw==
  template:
    metadata:
      creationTimestamp: null
      name: redis-password
      namespace: redis
    type: Opaque
