---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: redis-password
  namespace: redis
spec:
  encryptedData:
    redis-password: AgB11U7nCuW7NRoXQfRQ+kOhe1P/wRFchSsVGZ3XydPofzGEpYJYvP13hUCRDJ4iuR9YWuMtgSUGse13kgpgkLZ+ASVR7rZAypn9e1768Hq/YvTM9T+pvD9Iif5ly8c55pgTcRxuJiAhE1syToNWcaxpCOeSKDrXd2+vwAF2OD3wWgec7j5UoP5N6qJHsx6/jI5Lrh0UZ+4UDzIt6yUrQ1F8QjCFjTnR+k3Ir9GDalQ/FyCn+rt5DQjsxVKyOZK2Z4d2D3+x3ODegBxBgp8OKeov/TOvO4zJICMigQNFwCPLpoKWy799ZQ1jiFHk+lK52N+yB9XrOl1TaBq0aohOCVw+9PNYP6ZTbpAg2Pccr7drftSjYQaz8kljtMSEghyhLwimpJ7a8o/pBzRQoLkhtqm50Sdd85qsbNMLJ5gMUGXXTkHD/12r+ZmRgj06q/PpXC+kiLWZmniW25Xr3KpaRKM+tg7Pab86TehlZ2Z8Y/kPARFfMqPLwo0AGRXayufbIUNKVDXk9KOlblbARh9r9dvYUpfOGBE3mcuxIHMCR5YknOohAkGKJywgnOSTObZokRql7NaE5xOlXmdVcW9rthtWbDN75v9XzXfLfGanRBWnj9ahJffBOgfGnSXebuW0bVgu4teh7hm51E3yKHf4jRz7M9d8I5MLtNGQ9KWTdsyqJwOkEVeX7dDQhvrOgmchVSnXH9eAy0cHht8hgVnaplbnkzR1o9m1JSMZjE8XAadHSA==
  template:
    metadata:
      creationTimestamp: null
      name: redis-password
      namespace: redis
    type: Opaque
