---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rancher
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      ref: config
    - repoURL: https://releases.rancher.com/server-charts/latest
      chart: rancher
      targetRevision: 2.12.0-rc2
      helm:
        valueFiles:
          - $config/apps/rancher/values.yaml
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      path: apps/rancher/post-install
  destination:
    server: https://kubernetes.default.svc
    namespace: cattle-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
