---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  annotations:
    kubernetes.io/ingress.class: traefik-external
  labels:
    app: paperless-ngx
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`paperless.local.asztalos.net`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
      services:
        - name: paperless-ngx
          namespace: paperless-ngx
          port: 8000
  tls:
    secretName: local-asztalos-net-tls
