---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: paperless-ngx-notification-script
    namespace: paperless-ngx
    files:
      - notification.sh=notification.sh
  - name: paperless-ngx-config
    namespace: paperless-ngx
    env: paperless-ngx-config.env

resources:
  - postgresql-database.yaml
  - paperless-ngx-oauth-secret.yaml
  - paperless-ngx-redis-secret.yaml
  - paperless-ngx-postgres-secret.yaml
  - paperless-ngx-headers.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
