---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-oauth-secret
  namespace: paperless-ngx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-oauth-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
              "SCOPE":["openid","profile","email","offline_access"],
              "APPS": [
                {
                  "provider_id": "authentik",
                  "name": "Authentik",
                  "client_id": "paperless",
                  "secret": "{{ .secret }}",
                  "settings": {
                    "server_url": "https://auth.local.asztalos.net/application/o/paperless/.well-known/openid-configuration"
                  }
                }
              ],
              "OAUTH_PKCE_ENABLED": "True"
            }
          }
  data:
    - secretKey: secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-paperless-client-secret
