---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-postgres-secret
  namespace: paperless-ngx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-postgres-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        PAPERLESS_DBUSER: "{{ .paperless-postgres-username }}"
        PAPERLESS_DBPASS: "{{ .paperless-postgres-password }}"
  data:
    - secretKey: paperless-postgres-username
      remoteRef:
        key: paperless-postgres-password
        property: username
    - secretKey: paperless-postgres-password
      remoteRef:
        key: paperless-postgres-password
        property: password
