---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-app-secret
  namespace: paperless-ngx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-app-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        PAPERLESS_SECRET_KEY: "{{ .paperless-secret-key }}"
  data:
    - secretKey: paperless-secret-key
      remoteRef:
        key: paperless-ngx-app
        property: credential
