---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-ngx-redis-secret
  namespace: paperless-ngx
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: paperless-ngx-redis-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        PAPERLESS_REDIS: "redis://paperless:{{ .password }}@redis-master.redis.svc.cluster.local:6379"
  data:
    - secretKey: password
      remoteRef:
        key: redis-secrets
        property: redis-paperless-password
