apiVersion: v1
kind: Service
metadata:
  name: paperless-ngx
  namespace: paperless-ngx
  labels:
    app: paperless-ngx
spec:
  type: ClusterIP
  selector:
    app: paperless-ngx
  ports:
    - name: webui
      port: 8000
      targetPort: 8000
