apiVersion: v1
kind: LimitRange
metadata:
  name: databases-resource-limits
  namespace: databases
spec:
  limits:
  - type: Container
    max:
      cpu: "500m"
      memory: 512Mi
    min:
      cpu: 50m
      memory: 64Mi
    default:
      cpu: 200m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 64Mi
