apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  storage:
    size: 15Gi
    storageClass: longhorn-1r
  affinity:
    podAntiAffinityType: required  # Ensure pods are always on separate nodes
  bootstrap:
    initdb:
      database: app
      owner: app
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: authentik
        connectionLimit: -1
        ensure: present
        inherit: true
        passwordSecret:
          name: authentik-postgres-password
        login: true
  backup:
    barmanObjectStore:
      destinationPath: s3://homelab-cnpg-backup-production/cnpg-backup/
      endpointURL: https://s3.eu-central-003.backblazeb2.com
      s3Credentials:
        accessKeyId:
          name: cnpg-backblaze-secret
          key: application_key_id
        secretAccessKey:
          name: cnpg-backblaze-secret
          key: application_key
    retentionPolicy: "7d" # keep 7 days of backups
    schedule: "0 3 * * *" # daily at 03:00 UTC
