apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-backup
  namespace: databases
spec:
  cluster:
    name: postgres
  schedule: "0 3 * * *" # daily at 03:00 UTC
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
