apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  storage:
    size: 15Gi
    storageClass: longhorn-1r
  affinity:
    podAntiAffinityType: required  # Ensure pods are always on separate nodes
  bootstrap:
    initdb:
      database: app
      owner: app
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: authentik
        connectionLimit: -1
        ensure: present
        inherit: true
        passwordSecret:
          name: authentik-postgres-password
        login: true
      - name: paperless
        connectionLimit: -1
        ensure: present
        inherit: true
        passwordSecret:
          name: paperless-postgres-password
        login: true
  backup:
    externalObjects:
      - name: barman-cloud
        plugin:
          name: barman-cloud
          config:
            destinationPath: s3://homelab-cnpg-backup-production/cnpg-backup/
            endpointURL: https://s3.eu-central-003.backblazeb2.com
            retentionPolicy: "7d"
            data:
              compression: bzip2
            wal:
              compression: bzip2
              maxParallel: 4
            s3Credentials:
              accessKeyId:
                name: cnpg-backblaze-secret
                key: application_key_id
              secretAccessKey:
                name: cnpg-backblaze-secret
                key: application_key
