apiVersion: v1
kind: Namespace
metadata:
  name: databases
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: databases
spec:
  instances: 3
  imageCatalogRef:
    apiGroup: postgresql.cnpg.io
    kind: ClusterImageCatalog
    name: postgresql
    major: 17
  storage:
    size: 20Gi
    storageClass: longhorn-1r
  affinity:
    podAntiAffinityType: required  # Ensure pods are always on separate nodes
  bootstrap:
    initdb:
      database: app
      owner: app
  monitoring:
    enablePodMonitor: true
  managed:
    roles:
      - name: authentik
        connectionLimit: -1
        ensure: present
        inherit: true
        passwordSecret:
          name: authentik-postgres-password
        login: true
