---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-smtp-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: alertmanager-smtp-secret     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: smtp_password           # key in the Kubernetes Secret
      remoteRef:
        key: email-credentials
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
