---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgDtkJ7nQnqTLbrKqYs0bYPSvzZvVMF7Q9HXraVjDB0dYO/6P5Ag82hJHK0faBLYoWrLQHM1BqDpraiDh6VLFkgLenyFRAA2248AMQQlp2Zq8/sy5RWL6vsnwSRM5s232ZdH+lwdwsfTmA7FV1qOkdqHWYgkma6FKTx5FPlSF0RNt0vkQeJp54Kzenad0jPdQYUOgODnBZezeFzJEz9FmgF+TGJCNPTF8LJQFeVkC1Ue+HS9YKCocVHgakYwxc3WrxDJKYwjUNsigEBCBQqHxEMSipLjm7F+kDrDqNJ5z4RJVj5+zU/FTDD6eweRJzkyRCZhIWLm7MasZjoAPIy8eOXagbBhkbtbBxXzo9FexFBKrNLj95mSUGXKQ75mNELvet9hs96dZIB/VpUUdSh+kHWtaVfJJwZRc3fhYZegzQldWiXYpCWUrWffIx1z1gpbbFGHtsRDPQ/UapjqTRK4Q4xFKtDcRfdvDZc/SSd7i5ImkQ4FJEKnde41kgTwa91S3FceHrb0xxSeRwie6oIFISb2jX6EPBMDPRYdEiTprtb9o9zKH4iN5fReFHkqLDnyMZyXFnZw5pbXGljxfHxYvzfVYctag1HT8UB+BuO81no3NaMTzAoIqCEuXUJZRl/3nvbzfxRizEVwuO8QsATRFWRPOXWfyZobBicQbKVRY0uWGZfaHLYYACE1QX4F+58sna5AjzF3ek+s1nFZD6XaL639tYVQRR6OnuD6Ch9ur1W+nY32b9bOBas+SJK4uRl3u1VIzA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oauth-secrets
      namespace: monitoring
    type: Opaque
