---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-oauth-secrets
  namespace: monitoring
spec:
  encryptedData:
    GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: AgAc8phjdbhlUyEjXe7fx6rWfjoR2PbPtqOFU6eVlK8v/zxXDItcdmKN2AuzCzJnBgT1lz98TOiX8XG1SB8HK1dc++zYRVv0vYqNkvxtMXcrOW5lOSwBVzoL9QADVEgnb4g4xFxz3BmA61KcB3smlDmcBzYt8XvmB5p5zf6Jbc2YEgsXea8t0hTwAAWc6hW/O+OOuPfD+atLpZIXnQiPeFWHbTQwgIZA+YarzdtYQ/7DFSN8jIRJ+dwtQUUDiinJL13EuEZU1mBLlscB4J7YNx310M643evF5fUclvbAK33knoPis0mZQ2CCXpLuo2zJ3LS9M57n0tvWF9mlh0RaqiFdNd4OARW0I5lGVc9LZL7dvskSaW03tmezaXd54E9pZuthgWMt7pVjxQVYsmbr0vQ4/hNpKjB1NpyWokAhKr36KjTcIsyw3BUYpwO0zNt2USCKH/Z0K7hBlVhFqGh8khxypGPqw8cNBp91ctXTAX++PDhb5obPh6dGQHtoPmDXiz1jmCUsp5OvpJGF7frvgCTGNO+pGLuJy7Op0UCFKUkFie4Me0druVLeDfAROZtrhSJBEFW8a4bOB0et7tNZ6QSF6nyn1iZZZ5YxRc+FZMrGfvE0OWlyF4cBUyRENWDo/rtgDuy/WsNSiYAU4zRsRvQXKxccxDr7pM7HZBvpKZTJfTAD6Tgz9uhW+uSDg7DtMen/7KJ0kdMO3gkIhlHGNUBob4EFs4WLdpCgRZMXpuc8+0SBsdtGmun7055Vg3ij3X2sMPE=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-oauth-secrets
      namespace: monitoring
    type: Opaque
