---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: kube-prometheus-stack-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgArLUq7U6YSpQBb5d1bJb6t0RTMbBm/58owGrhhy/QbufJbdynzZkCTfXfd4pTp3oCoze2ACygXPu64VRofX4WD36fhjOjhiMfvcn/14rrUEGmjMiApI7Ge5XzhAk3+8JJCUr8H2RSCZxC5UYfovhXFgCvHO2/lJLLZPf7wlqQzvCnE72I6XILK9Gi03HXqbus/YrjtFuOE1mJPbYSJ2KM7h2bYY2F2MnSbCy3FuWIrsYU6mYOlNMWMXNPCIvoKmG7rdITBFs9S+S2hAwGMKpKuPLP++RZ+Ss7bAwEueVVJd1wygWGKF7JkTT6s+woI+ix8M68KITzh0sOZuvqAfpMnqUef86iv7nYyYSAz7W+LA31nuOvqxjughI8tnMFPfGL/gR0txUqfX6PIBILtjaZoYNO8th654K4oLKEN7vf5pRZ66LYfXZ97+iL0QecTI1b/O2Y10nG9TrHTxnWmrMebkVdZLkftuTq+hvhIkPPe10/RpdU2/ILT6I+lRy2X6sf8xmEyZv0i7Qvwu79TSFSHrpcYRe2yBL4+u2/h8r5EvpC2M/ib29HhZBcRYftflGHdJsjss8gdOuTQwmkQoEzotlOyQNGZ2cE2szfcjMW6+WOZzlDQ/W/3Y6ME88FXR0Vq4YGM5GPSlUVO7jQxC7y3XJEthnvc9CpXs/shKMq9TYUcQoyWnWvtddPtOQcQe0wqZC/lDU/XCVDZ2L9k75kBWIO2MmWXhQgZaPtsGrgrqrwfRyyRiCVzXOYqpw==
    admin-user: AgBJpgJeRdr7NRthQDHguqaQ+kZ8w1Z6DuC2Of5j2T1IESIxZHpGfPG1cLfDNqPRYJeUwNMrY3z70dFsCLtj+JGUIKisoW1xFBxvefmfnCNVioxzdqyMtF30sYQAohPOEFaeAh0Rpia5kVb/5CDvqTwdqcvpGee0S7b8VRkqalKiDFp5J/412nG/77WjBrXvM5U7THg34POcYXWrQCga9Sd8wIFOhgKkFsZKC4kkNbyo6h5HNvA0IWCu6u6YLRZ225+iC12zJRZPAUMpUuf4E8cuL+mmkztcPmBGRIgxLzmw5EiN0kqEFvkmjhn6hL5R0eTLPK2xsDFJwk5WC0dPQXH+79BAmcGcfvlJg1AVKw8HmuEJ+5lcyo4D/nW7W+CTS+XSTXmfM2bHdIXogxioY+KH5tOxFj3Jufr/JDXU9nieKQy5dTRuH5o6YJGyRRSphORcGL1HmMlWVTe998ML7vS3zD9wJf3TbkDqSwT8+FH5w6bQdSn9gf2NPkhxk2o5sw+yygA6GOMPCHjirb4x1GQCsyjXbon7dUlKMQ7LLG29LYNVvSu1yDeyQptgKihoy/Y9VIBCLEZO+jb9yA4S7e+r2AJrbW5RYBGwdQUK7GJC5QaLWcMWpGI6/4Qv3hr3Qa4p4BlTQW1UtQZn/ZQ5X11So4S6k+nNjYnQFHJmZ0hf/ETZz1lAdFmoVLHUf9p/z5VLlFoYKQ==
  template:
    metadata:
      creationTimestamp: null
      name: kube-prometheus-stack-grafana
      namespace: monitoring
    type: Opaque
