---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: grafana-secrets     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: admin-user           # key in the Kubernetes Secret
      remoteRef:
        key: grafana-secrets/admin-user
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: admin-password           # key in the Kubernetes Secret
      remoteRef:
        key: grafana-secrets/admin-password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET         # key in the Kubernetes Secret
      remoteRef:
        key: grafana-secrets/GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
