---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secrets
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: grafana-secrets     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: admin-user           # key in the Kubernetes Secret
      remoteRef:
        key: grafana-secrets
        property: admin-user
    - secretKey: admin-password           # key in the Kubernetes Secret
      remoteRef:
        key: grafana-secrets
        property: admin-password
    - secretKey: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET         # key in the Kubernetes Secret
      remoteRef:
        key: grafana-secrets
        property: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
