apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  namespace: monitoring
  name: alloy-health
  labels:
    app: alloy
    app.kubernetes.io/name: alloy
    app.kubernetes.io/part-of: alloy
    app.kubernetes.io/component: alloy
    app.kubernetes.io/instance: alloy
spec:
  groups:
    - name: alloy-core-health
      rules:
        # 1. Alloy metrics endpoint down
        - alert: AlloyExporterDown
          expr: up{job="alloy"} == 0
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: "Alloy metrics endpoint unreachable"
            description: "Prometheus cannot reach Alloy's /metrics exporter. Alloy may not be running or scraping logs."

        # 2. Alloy ingest errors
        - alert: AlloyLogCollectionErrors
          expr: alloy_ingest_errors_total > 0
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Alloy log collection encountered errors"
            description: "Alloy self-exported error metrics are nonzero. Check Alloy subsystem logs."
