{
 "title": "SolarEdge",
 "description": "An imperfect but useful dashboard for getting started with https://github.com/dave92082/SolarEdge-Exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AC Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "AC_Power*10^AC_Power_SF", "legendFormat": "AC Power" }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 1, "y": 9 },
   "targets": [
    { "expr": "Status" }
   ]
  },
  {
   "title": "Status (Vendor)",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 9 },
   "targets": [
    { "expr": "Status_Vendor" }
   ]
  },
  {
   "title": "Heat Sink Temperature",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    { "expr": "Temp_Sink*10^Temp_SF" }
   ]
  },
  {
   "title": "SunSpec_Length",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 1, "y": 12 },
   "targets": [
    { "expr": "SunSpec_Length" }
   ]
  },
  {
   "title": "SunSpec_DID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 12 },
   "targets": [
    { "expr": "SunSpec_DID" }
   ]
  },
  { "title": "DC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "DC Current",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "DC_Current*10^DC_Current_SF " }
   ]
  },
  {
   "title": "DC Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "DC_Power*10^DC_Power_SF" }
   ]
  },
  {
   "title": "DC volts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "DC_Voltage*10^DC_Voltage_SF" }
   ]
  },
  { "title": "AC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "AC Current",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "amp" }
   ],
   "targets": [
    { "expr": "AC_Current*10^AC_Current_SF" }
   ]
  },
  {
   "title": "AC Lifetime Energy production",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "watth" }
   ],
   "targets": [
    {
     "expr": "AC_Energy_WH*10^AC_Energy_WH_SF"
    }
   ]
  },
  {
   "title": "AC VAR Reactive Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "voltampreact" }
   ],
   "targets": [
    { "expr": "AC_VAR*10^AC_VAR_SF" }
   ]
  },
  {
   "title": "AC VA Apparent Power",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "voltamp" }
   ],
   "targets": [
    { "expr": "AC_VA*10^AC_VA_SF" }
   ]
  },
  {
   "title": "AC Frequency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 69 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "AC_Frequency*10^AC_Frequency_SF > 0"
    },
    { "expr": "50" }
   ]
  },
  {
   "title": "AC % Power Factor",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    { "expr": "AC_PF*10^AC_PF_SF" }
   ]
  },
  {
   "title": "AC Voltage AB",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "volt" }
   ],
   "targets": [
    { "expr": "AC_VoltageAB*10^AC_Voltage_SF" }
   ]
  },
  { "title": "DC vs AC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 } },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    { "expr": "DC_Power*10^DC_Power_SF", "legendFormat": "DC Power" },
    { "expr": "AC_Power*10^AC_Power_SF", "legendFormat": "AC Power" }
   ]
  }
 ]
}