---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-redis-secret
  namespace: argocd
spec:
  encryptedData:
    redis-password: AgCUwHUyEGxLcokDrRLmtHNqJn4Ct1PXUTvfW2A8f55BTI0eshmLtYp59+KvCxICfyzYjYketX+sk6jrVO6rMPIyWprmowdQcvfhOlQqooEdx312iCBAOFCOLEYaoI8M6xqZPvSxWkDuwigHFhYz1XJGzAuKWureN0DObq+pjTLSrUCm+pmtOGT0jpVWapeDjHWeuf4iaLUEpvCTGaCUNtIZ8sT8wpUuZf6xYxWYTljSObszZ5b4ppcSnhsAtteyhc450bfzLCNdupqD+mP+n6Y2V5VCinXj+u0VizEJyGtu1rZjYgfghVLHQ2SuIWIPX0UfCIzk+VlKea/K65zooSwMd3d9shtRZCgxliH8KMfr5BAdM4qHIlxl91Y1Wnk7UH+eFJCviZqcvfr6iP4I/O8vO/iwqdXS/TiZiahAqxwQlJkhT7/RQhGLQrCkpv0SaGwHDjYZzADWJ7MMh3zGvMOj1ccohCxVPBoW+Nnf8heDjG56fQiEDtlAM2fSf65m+SRGccLhaACSsahz8rz9ciMtgtEB37RCr7k/T1We8wHUFONo0ANcnvBOf4yAnyRzBB2xxZPsjuHatkS2RnMYxzd8AghUw7E4ZowuU9gkAE30xamcN0S7hTk6wcU8pIKpkFEqnxZS6mBufLXI3mV2PzBWrmR12pF0goHunw3wee7SNQO7jSy+tSaZqvEzXohRFK4loBFk4csaMWUPodh5jIJm
    redis-username: AgBu8Tu+ssY/FSCHupDJGFCXjsofAF008HZwTwo6hewE1dG7Md3pXuE1V6wMS0Zu+0s7lAp2OkUZcftLXmDcD9CuVitZWEPegkeg7DUQG+u2zGT2vJj9cboaJ8FNC4J7aW3ApNfj6d5yb6kFxciLZxG98BxENCPGTDMpU0ZvroSs5pSW/xVDYWuOu3MRx08r+DLSAzzzgkcph5Rna/vwQYtDlwYy7sOwRJQqF1zgWOzPflsluF17hkFoXfQISAg5AlZ2aBjpu5Xi4YANMq2M9uiXSF3tg09HdqcH59vioU3F6Z9Zm4Qiai8Z5L4KzxdAojeu5dnpV2o84q3wGTeCNFODzLelNJkFfWFfX7rrwaBN2HgMCZ6myzVbnGLa/CTQFqFh3MYkdoRhURAy+q3n9N/H8BgkLE0XY92HyV2JgsjlULfmsqDsCFTRTjjidsQCqUWsVxUX6qh+4vmoR6APG6Qyx69O1P3eUEKsM8Qwo2XbFxZG8Vu/Phfm2c2U0v4pgnqnBRNH/qJ4BDT1JdX9BFE65ghj6rGsFhNMFA326XkMRD6pHGMPDGxAaXFHZxvtlCg2JLHahGwVd+vx4ZohWRcno/hHaPfHqqngq1uAf1PbhXmgw6HwR98dpmrXjso/F4izc7XPRIpkLttx+Dzco2PXCHE1XZKpbhgjoq/H1UcMwPV5q3yw4ifLySUO2zd3fjUilCUtcnE0
  template:
    metadata:
      creationTimestamp: null
      name: argocd-redis-secret
      namespace: argocd
    type: Opaque
