apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-notifications-cm
  namespace: argocd
data:
  service.webhook.apprise: |
    url: http://apprise.apprise.svc.cluster.local:8000/notify/apprise
    method: POST
    headers:
      - name: Content-Type
        value: application/json
  template.app-sync-succeeded: |
    webhook:
      apprise:
        method: POST
        body: |
          {
            "tag": "argocd"
            "title": "ArgoCD: {{.app.metadata.name}}",
            "body": {{ printf "Application %s synced successfully at %s." .app.metadata.name .app.status.operationState.finishedAt | quote }},
            "type": "info"
          }
  template.app-sync-failed: |
    webhook:
      apprise:
        method: POST
        body: |
          {
            "tag": "argocd"
            "title": "ArgoCD: {{.app.metadata.name}}",
            "body": {{ .app.status.operationState.message | quote }},
            "type": "error"
          }
  template.app-health-degraded: |
    webhook:
      apprise:
        method: POST
        body: |
          {
            "tag": "argocd"
            "title": "ArgoCD: {{.app.metadata.name}}",
            "body": {{ printf "Application %s health degraded: %s." .app.metadata.name .app.status.health.status | quote }},
            "type": "warning"
          }
  trigger.on-sync-succeeded: |
    - send: [app-sync-succeeded]
  trigger.on-sync-failed: |
    - send: [app-sync-failed]
  trigger.on-health-degraded: |
    - send: [app-health-degraded]
