---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-credentials
  namespace: argocd
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: argocd-credentials     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: redis-username            # key in the Kubernetes Secret
      remoteRef:
        key: argocd-credentials/redis-username
    - secretKey: redis-password               # key in the Kubernetes Secret
      remoteRef:
        key: argocd-credentials/redis-password
    - secretKey: oidc.authentik.clientSecret                 # key in the Kubernetes Secret
      remoteRef:
        key: argocd-credentials/oidc.authentik.clientSecret
