---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    webpassword: AgBU6uQWI5P30TxF35TbTrDoNDNqLjLgHOHsGPJEXbEMobfQUCRVBTG1lbp5LOsTW0WoGmh9mv17coyoeZtfJTh+aOsnmomOskt0xYusHp69Uu29aDqglFV3JdQIJxAx0Lzf2NAOWnbDcxNYhOSajHSZC0wLbYBoxaW+421kh8FVDsq1Y2fxdttM+vpT0QBb9ha47Yp3hMLRgWALnhBEZ6DNYL0uscykKoXfLnY8AaZDHtPmxZO9I2l9hBjWvYZC4TDpXd+4M8ZZJXrBhnXd/Xkx5+sa9zY1TrUHFI0DiyVhrRDtX7zeWG1/9no0SgsbNSNF+43MRAfErUxlksFQj4lHgptQ/tBkrDX9TBYcjpyHk9UpmSgdOrzCvNWvLIghyA/LCgBs/3qyX3Cs0UtPlQw3Yy5kJJIvp6Mqz5ya2wmRM9TTOLisj2K6mhSmoIXDyA3YvhTDuG9gJYupv1DnemQPJVVg/dzFQ2Psx1f5IqwCycCvT+L54pc8LjuuLSBapAMq9EYbplVvCnfU/JTLdHfkh32r5d41LQEX09kMGkFsctsY0gcDloAnF+E8fTVlsyB8e5NR05Spn+OKehcbE+AFo35VQtuXpvkY2VuzWivc+qPhTyhezKVdBHC7hejN52NqdnExlGz6ZXWWk0cGh5Y8Es/fqJSe7KBUUnXq40xchpiaEl9rpf7F5fCn029a2+/2fdxzRyV/zEGrO0G85QaN6i3q+6KqG9JBkTLPhxX4jL6gucu8hThI/A==
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
    type: Opaque
