---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    webpassword: AgC9MmbO1xilYZfaI+1X9ZHVwzV7xooInyV0+cOM4+9acjc8FszWa+r50ckswUAVkhJgkwWhHIK2gqVAgXBfjp51WyfYDYpscaqkU9uRNoEWFWG5oZoLWbRZVSELBMaI4t82E0kYQ5h1fsBQQNqxmHkImosgirllq+ZP9XGtg2/OHHO51QD2768j9vImvRtEHc0fasuKVatjTEW6hIC+wrbO+CUytTXoCprVWCsXNjPGIU7XMsaJk+zrkIYh5NxKrhNBg5jHFonuycXoi+Y2C8S++ffP0SJ6tXw+eln/R7LXWj151NfXDHnR7Q/qHChH7cXAS5vZheriYKJQzvD0z0UszvJsXlJCmtMvykvji0JCUC1bY2c4Cl1liGgdYZdZoIjnhIEUZitI7H6IVDXBSmXHFiuXob1spd8TJ0UBvVGX8od1bI5HcCjlG8Pkz4l8ZqK8hTa9fO/L17rsYagRA1j0ZAPXD7+QGVM7L0IZrRoQ2AHBwBsyLswdymgZDcIIaJhPT/we0b3N8pMu2r52z8hVs5TFQfFZwJ21XcH0nyjsFudwcalj856awPenHCkWPvcIVTlJH8leAflIRTGXHNFJwv5/EYEFRp9tvAhsepKKJtH9e/mXbMzGS9m6Lhqxk3iFaZH/4GZ0WZEUAjelI9oteybHzutubHWE71VARwIoo3YxmuoizQK+30b9oVJm2bGq5Jwju0IEYM1QgsUEXsrf+dMrjYqjOJR/guKQhQAEddEeLmdr6Q5wMUfjwgw=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
    type: Opaque
