apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-exporter
  namespace: pihole  # or the namespace where your exporter runs
  labels:
    release: prometheus-operator  # match your Prometheus Operator’s selector if needed
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole  # or the label used by your exporter service
  endpoints:
    - port: prometheus  # or the port name used by your exporter service
      interval: 30s
      path: /metrics
