---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: reflector
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      ref: config
    - repoURL: ghcr.io/emberstack/helm-charts/reflector
      chart: reflector
      targetRevision: 9.1.7
      helm:
        valueFiles:
          - $config/apps/reflector/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: reflector
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
