---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apprise-config
  namespace: apprise
spec:
  refreshInterval: 6h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: apprise-config     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: apprise.yml            # key in the Kubernetes Secret
      remoteRef:
        key: apprise-config/apprise.yml  # 1Password item name
