---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - apprise-config.yaml
  - mailrise-config.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingressroute.yaml
  - prometheus-alarms.yaml
