apiVersion: v1
kind: ConfigMap
metadata:
  name: mailrise-config
  namespace: apprise
data:
  mailrise.conf: |-
    configs:
      unattended:
        mailrise:
          title_template: "[ $from ] $subject ($config)"
        urls:
          - apprises://apprise:8000/apprise/?overflow=split&tags=unattended-upgrades

      flexget:
        mailrise:
          title_template: "$subject"
        urls:
          - apprises://apprise:8000/apprise/?overflow=split&tags=flexget

      grafana:
        mailrise:
          title_template: "$subject"
        urls:
          - apprises://apprise:8000/apprise/?overflow=split&tags=grafana

      "babybuddy":
        mailrise:
          title_template: "$subject"
        urls:
          - apprises://apprise:8000/apprise/?overflow=split&tags=babybuddy

      "*@*":
        mailrise:
          title_template: "[ $from ] $subject ($config)"
        urls:
          - apprises://apprise:8000/apprise/?overflow=split&tags=admin
