apiVersion: v1
kind: LimitRange
metadata:
  name: loki-resource-limits
  namespace: loki
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
      memory: 1Gi
    min:
      cpu: 10m
      memory: 32Mi
    default:
      cpu: 20m
      memory: 550Mi
    defaultRequest:
      cpu: 10m
      memory: 100Mi