---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
  namespace: unbound
  labels:
    app: unbound
    app.kubernetes.io/name: unbound
    app.kubernetes.io/part-of: unbound
    app.kubernetes.io/instance: unbound
  annotations:
    ignore-check.kube-linter.io/no-read-only-root-fs: "Unbound requires a writable root filesystem for /var/unbound"
spec:
  replicas: 1
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: unbound
  template:
    metadata:
      labels:
        app: unbound
        app.kubernetes.io/name: unbound
        app.kubernetes.io/part-of: unbound
        app.kubernetes.io/instance: unbound
    spec:
      containers:
        - name: "unbound"
          image: klutchell/unbound:1.23.1
          imagePullPolicy: IfNotPresent
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false # prevent sudo, etc.
            privileged: false               # prevent acting like host root
            capabilities:
              drop: [ALL]
              add: [NET_BIND_SERVICE]  # Only if using privileged ports (e.g., 53)
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          ports:
            - name: "dns-udp"
              containerPort: 53
              protocol: "UDP"
            - name: "dns-tcp"
              containerPort: 53
              protocol: "TCP"
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: unbound-socket
              mountPath: /var/run/unbound
            - name: unbound-main-conf-volume
              mountPath: /etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: unbound-forward-conf-volume
              mountPath: /etc/unbound/forward-records.conf
              subPath: forward-records.conf
        - name: "exporter"
          image: cyb3rjak3/unbound-exporter:0.4.6
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          securityContext:
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false # prevent sudo, etc.
            privileged: false               # prevent acting like host root
            capabilities:
              drop: [ALL]
          ports:
          - name: metrics
            containerPort: 9167
            protocol: TCP
          volumeMounts:
            - name: unbound-socket
              mountPath: /var/run/unbound
          args:
            - -unbound.host=unix:///var/run/unbound/unbound.ctl
      restartPolicy: Always
      volumes:
        - name: unbound-socket
          emptyDir: {}
        - name: unbound-main-conf-volume
          configMap:
            name: unbound-main-conf
        - name: unbound-forward-conf-volume
          configMap:
            name: unbound-forward-records-conf
      securityContext:
        runAsNonRoot: true
        runAsUser: 101  # Must match Unbound's user/group for socket access
        runAsGroup: 102
        fsGroup: 102  # Match "unbound" group in Unbound images
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - unbound
              topologyKey: kubernetes.io/hostname
