---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: unbound
    spec:
      containers:
        - name: "unbound"
          image: klutchell/unbound
          imagePullPolicy: IfNotPresent
          ports:
            - name: "dns-udp"
              containerPort: 53
              protocol: "UDP"
            - name: "dns-tcp"
              containerPort: 53
              protocol: "TCP"
          resources: {}
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: unbound-socket
              mountPath: /var/run/socket
            - name: unbound-main-conf-volume
              mountPath: /etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: unbound-forward-conf-volume
              mountPath: /etc/unbound/forward-records.conf
              subPath: forward-records.conf
        - name: "exporter"
          image: cyb3rjak3/unbound-exporter:0.4.6
          imagePullPolicy: IfNotPresent
          resources: {}
          ports:
          - name: metrics
            containerPort: 9167
            protocol: TCP
          volumeMounts:
            - name: unbound-socket
              mountPath: /var/run/socket
          args:
            - -unbound.host=unix:///var/run/socket/unbound.ctl
      restartPolicy: Always
      volumes:
        - name: unbound-socket
          emptyDir: {}
        - name: unbound-main-conf-volume
          configMap:
            name: unbound-main-conf
        - name: unbound-forward-conf-volume
          configMap:
            name: unbound-forward-records-conf
