---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: unbound
spec:
  replicas: 1
  selector:
    matchLabels:
      app: unbound
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: unbound
    spec:
      securityContext:  # Applies to all containers
        fsGroup: 1000   # Ensures volume write permissions for group
        seccompProfile:
      type: RuntimeDefault
      containers:
        - name: "unbound"
          image: klutchell/unbound
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000  # Match "unbound" user in Unbound images
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
              add: [NET_BIND_SERVICE]  # Only if using privileged ports (e.g., 53)
          ports:
            - name: "dns-udp"
              containerPort: 53
              protocol: "UDP"
            - name: "dns-tcp"
              containerPort: 53
              protocol: "TCP"
          readinessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 53
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: unbound-socket
              mountPath: /var/run/socket
            - name: unbound-main-conf-volume
              mountPath: /etc/unbound/unbound.conf
              subPath: unbound.conf
            - name: unbound-forward-conf-volume
              mountPath: /etc/unbound/forward-records.conf
              subPath: forward-records.conf
        - name: "exporter"
          image: cyb3rjak3/unbound-exporter:0.4.6
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000  # Must match Unbound's user/group for socket access
            runAsGroup: 1000
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
            capabilities:
              drop: [ALL]
          ports:
          - name: metrics
            containerPort: 9167
            protocol: TCP
          volumeMounts:
            - name: unbound-socket
              mountPath: /var/run/socket
          args:
            - -unbound.host=unix:///var/run/socket/unbound.ctl
      restartPolicy: Always
      volumes:
        - name: unbound-socket
          emptyDir: {}
        - name: unbound-main-conf-volume
          configMap:
            name: unbound-main-conf
        - name: unbound-forward-conf-volume
          configMap:
            name: unbound-forward-records-conf
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - unbound
              topologyKey: kubernetes.io/hostname
