apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: unbound-exporter
  namespace: unbound  # or the namespace where your exporter runs
  labels:
    release: prometheus-operator  # match your Prometheus Operator’s selector if needed
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: unbound  # or the label used by your exporter service
  endpoints:
    - path: /metrics
      interval: 30s
      targetPort: metrics
      honorLabels: true
      relabelings:
        - action: replace
          regex: ^(.*)$
          replacement: $1
          separator: ;
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: nodename
  namespaceSelector:
    matchNames:
      - unbound
