---
apiVersion: v1
kind: Service
metadata:
  name: unbound
  namespace: unbound
  labels:
    app: unbound
    app.kubernetes.io/name: unbound
    app.kubernetes.io/part-of: unbound
    app.kubernetes.io/instance: unbound
    app.kubernetes.io/component: unbound
spec:
  selector:
    app: unbound
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
      targetPort: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: metrics
      protocol: TCP
      port: 9167
      targetPort: metrics
  type: ClusterIP
