---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-database.yaml
  - cake-order-postgres-secret.yaml
  - cake-order-app-secret.yaml
  - migrate-job.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
  - purge-cronjob.yaml
  - servicemonitor.yaml
  - prometheus-alarms.yaml

labels:
  - pairs:
      app.kubernetes.io/name: cake-order
      app.kubernetes.io/part-of: cake-order
      app.kubernetes.io/instance: cake-order
      app.kubernetes.io/component: cake-order
    includeSelectors: false
