---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: transmission-notification-script
    namespace: transmission
    files:
      - transmission_notification.sh=transmission_notification.sh
  - name: transmission-config
    namespace: transmission
    env: transmission-config.env

resources:
  - transmission-secret.yaml
  - pv.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: transmission
    app.kubernetes.io/part-of: transmission
    app.kubernetes.io/instance: transmission
    app.kubernetes.io/component: transmission
