apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-data
  namespace: transmission
  labels:
    app: transmission
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-share
  resources:
    requests:
      storage: 1000Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: transmission-config
  namespace: transmission
  labels:
    app: transmission
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 512Mi
