---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-postgres-password
  namespace: databases
spec:
  encryptedData:
    password: AgBLrbIXOvDQyJMfzDGmoFxTDMp2haGwO3qVCDcJeTBVN7uXP4Hp/ISExPWF92dmh0PJQijHCh2oA1VNjS6f5rBz6N/oTM0+sYiccPyJ2u2m5SQuUZrZ3scN45Jd6KwoyMZyvdOOIWnTagFghUdWdfjoR4aEtDGNQffFYxKn29yW2bTHpcn0gYFaoQ3y9kWlbuW6fH20RHZtjneHSSovDLnYirV4gbq0H9b90DE9t0FIdSNUP9Uv3aC+QEjpkaE5oxzk/TLes95Qld2JSk5GlMBE/zXLb7Bx3aepRhRNo0lGqYSQWBV7gC4uJ2ObliWTrviZM4iAl4pZKo1yNT05+epjXEs0wlmw3jt5WzyU4HqTM7W9mnjZRarIX9vPDNH/aqFsdrEmHFrK7GwUUrFhtTCUSxVjz+vDuoU3IP8HqoE+aPM3R9YUq/qwzbFmRIHuFsZMPdfl4t5nqzSYCE5ESfVin5UJkj2cNGBg/iWXAwKG7QCOqpV6Mg9DySqdOI36olL2YKtZSv4f0DNjirRv0FEAZeGg03+OUHXRmClyaA/STC1Zfb1//nlxAR6e5gvV58Lcz6I1Nv/f8PGOOAqbNn5nGAHzaJOnWnVyptv54dY5aG6xB8+ja2JOMpQdd9wRF8qAEa2gM5mpMrdkXwtKw+GqmTP6Xz2RpAFQuCCof1tw3ybAYIwG+ffzXyMaaTH+4LGHEd8uZPpMEkAMdsRfTVv/a+ovv3SonDXJ1QwIlXGFvYKbxnR9VlsWSQ==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-postgres-password
      namespace: databases
    type: Opaque
