---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-postgres-password
  namespace: databases
spec:
  encryptedData:
    password: AgAYpMwK/IfwAx/xaead+XnkQMZIagQGlQzpwpvxGQTs+pIM6x7JMFAzdkoEky0oLUFarQ7nEJl8QeiKm0Buv9VZt5Q9YK5o4MTAEToGAj16My/IIXqXUMHGlmAO1Ik+7NkyaOvbM7mw1jSsZtjJfi4KqzhLLbRs37gES8prdLO1aKNI2LVkM+34XfXVgntc4CnJrPhhfQm2HkCdB8FMtFm8ejpkjz/PSvFK3yz1c+yZIgVI9u4yEmWdsAVqJDkQ5ct+u+q4Z8d4HchmaNl9UY+bonm7q8ONZi1+8TliRxLMOQeO8/HclTIWiZ/L5D33Mstc3If4iGrNTghofxddMMe1mvObKy0SEA7BgI7cOzLdciQRhD5LI3uXVn1Pahj/2g86NXJut+qAJsuPoKXAZynq0BMHT7X7HlilYLl2Yn5GG7sMBsUJNZ3v3tElTHFN+d5w/NWU2KEL19+r1AESxJlJHCM7TdU1GVUaLzdQBv0LKjy9rgp0AJNAjuLsvq9KvU1KxUClpvAXQyw9H+/p42HSokbqk7raWT7PnXyjTrAJfzlSaMJEGrSr3soycviYHVosZVFBSxlyZk8gLT4lqMaskN+PAhItfBMGRt6aZ1GkPRH3M0OGc5j6ZAKXgkt900S55vh3uE9ub45dkI3MRyUYVJXTWEhECfLD3fgAxC5ydLqojs2zBA4rQRZqRG7H9BJAQpGgD4f5vCJ3LxdXDE2WjH4D4jj3hDjJ8S5mJhVk1hniVLehkv7Z
    username: AgCknc8S/dwHCTBrYU/fl8hdI19flh9oUJs+nWhuV5yAWRzzIGPEr2OxkH4WcKSPlUCofWPkTg2ntMgYFbLwJUP0C3vdfEdv2PWG44xe40T1zMwYBSf/NYUj7gSrx5bKzvoMVW+W38nUrEMIMiP8SqUdXoda4PPNnXsE8mffOS7nugSHs5DQjCZRSbnMCIX5+yyqO2ZSG3bc9Wdph1APt87Je/Lxgll+5ANt3V8EylnqYxERiibopHIKXFTEfFveNJF3l0SYBh3mIdE3Efbri5Z2aO1L5WlIMPN1WOBNWs4E44BPq3jLqpbBczq1Qx7TAOR1GGPBejFjK+3Wo/QKlgDyQrcvUvbaKlT0MQfvHEwlL9UPATyRg1xQllDEL2m7PeW58fxvGI51Pt45QE8keh/Q3U/Fq4WgEgEEkIQqG1kMJd0k9UXvSU9kcTSQmg6s1WBn/L676dADs0TVjS1YoOM43fEKhrResMBPEF9udD+8BrZGH19KvhrQpvq+8fS9K1F1Nk6tKD6QZR9fyY5GMo8c2ds/UxxKN/rmHf1JPxJpHfSoTi6YrCEc+Cn5KPmumO3n3uNMGp5MP1Ut4DXFx2lnxK3+but033Mnpjmg8CA3r1MPbQ8u04SGveBCPJmhxl85smcISJWpbXfN+U6Kc+B7ugmaDZUtNB4Jvu+U3/Idpb5HWciH2EoIYUMCzT1Xqtx4bMR9d4CWP3A=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-postgres-password
      namespace: databases
    type: kubernetes.io/basic-auth
