---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-password
  namespace: databases
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-password
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: authentik-postgres-password/username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: authentik-postgres-password/password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
