---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgres-password
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: authentik-postgres-password
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      remoteRef:
        key: authentik-postgres-password/username
    - secretKey: password
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
      remoteRef:
        key: authentik-postgres-password/password
