---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-postgres-server-cert
spec:
  secretName: my-postgres-server-cert
  usages:
    - server auth
  dnsNames:
    - postgres-lb.local.asztalos.net
    - postgres-rw
    - postgres-rw.default
    - postgres-rw.default.svc
    - postgres-r
    - postgres-r.default
    - postgres-r.default.svc
    - postgres-ro
    - postgres-ro.default
    - postgres-ro.default.svc
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-postgres-client-cert
spec:
  secretName: my-postgres-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io

