apiVersion: postgresql.cnpg.io/v1
kind: ClusterImageCatalog
metadata:
  name: postgresql
  labels:
    images.cnpg.io/family: postgresql
    images.cnpg.io/type: system
    images.cnpg.io/os: trixie
    images.cnpg.io/date: '20260622'
    images.cnpg.io/publisher: cnpg.io
spec:
  images:
    - major: 15
      image: ghcr.io/cloudnative-pg/postgresql:15.18-system-trixie
    - major: 16
      image: ghcr.io/cloudnative-pg/postgresql:16.14-system-trixie
    - major: 17
      image: ghcr.io/cloudnative-pg/postgresql:17.10-system-trixie
    - major: 18
      image: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie
