---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cnpg-backblaze-secret
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: cnpg-backblaze-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: application_key_id
      remoteRef:
        key: cnpg-backblaze-secret
        property: application_key_id
    - secretKey: application_key
      remoteRef:
        key: cnpg-backblaze-secret
        property: application_key

