apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/cloudnative-pg/postgres-containers/main/Debian/ClusterImageCatalog-bookworm.yaml
  - certificates.yaml
  - longhorn-storageclass.yaml
  - authentik-postgres-password.yaml
  - paperless-postgres-password.yaml
  - cnpg-backblaze-secret.yaml
