---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: paperless-postgres-password
  namespace: databases
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: paperless-postgres-password
    creationPolicy: Owner
    template:
      type: kubernetes.io/basic-auth
  data:
    - secretKey: username
      remoteRef:
        key: paperless-postgres-password
        property: username
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
    - secretKey: password
      remoteRef:
        key: paperless-postgres-password
        property: password
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
