---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 1password-connect
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      path: apps/1password-connect/pre-install
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      ref: config
    - repoURL: https://1password.github.io/connect-helm-charts
      chart: connect
      targetRevision: 2.0.2
      helm:
        valueFiles:
          - $config/apps/1password-connect/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: 1password-connect
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
