---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "multus-iot",
          "namespace": "kube-system",
          "interface": "eth0.20",
          "ips": [ "10.10.20.13/24" ],
          "mac": "ce:ff:6a:78:88:a1"
        }
      ]
spec:
  containers:
  - name: sample-pod
    command: ["/bin/ash", "-c", "trap : TERM INT; sleep infinity & wait"]
    image: alpine
