---
apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  namespace: default
  annotations:
    k8s.v1.cni.cncf.io/networks: |
      [
        {
          "name": "multus-iot",
          "namespace": "kube-system",
        }
      ]
spec:
  nodeSelector:
    kubernetes.io/hostname: "cheryl"
  containers:
  - name: sample-pod
    image: nicolaka/netshoot
    command: ["/bin/sh", "-c", "trap : TERM INT; sleep infinity & wait"]
