---
apiVersion: postgresql.cnpg.io/v1
kind: Backup
metadata:
  name: postgres-adhoc-backup
  namespace: databases
spec:
  cluster:
    name: postgres
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
