---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nut-exporter-config
    namespace: nut-exporter
    env: nut-exporter-config.env

resources:
  - nut-exporter-secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - grafana-dashboard.yaml
  - ingressroute.yaml
  - prometheus-alarms.yaml
