---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: nut-exporter-config
    namespace: nut-exporter
    env: nut-exporter-config.env

resources:
  - nut-exporter-secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingressroute.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: nut-exporter
    app.kubernetes.io/part-of: nut-exporter
    app.kubernetes.io/instance: nut-exporter
    app.kubernetes.io/component: nut-exporter
