---
apiVersion: v1
kind: Service
metadata:
  name: nut-exporter
  namespace: nut-exporter
  labels:
    app: nut-exporter
spec:
  selector:
    app: nut-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9199
      targetPort: http
  type: ClusterIP
