---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: etcd-backblaze-secret
  namespace: kube-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: etcd-backblaze-secret
    creationPolicy: Owner
    template:
      type: etcd.k3s.cattle.io/s3-config-secret
      data:
        etcd-s3-bucket: "homelab-etcd-backup-production"
        etcd-s3-endpoint: "s3.eu-central-003.backblazeb2.com"
        etcd-s3-region: "auto"
        etcd-s3-access-key: "{{ .application_key_id }}"
        etcd-s3-secret-key: "{{ .application_key }}"
        etcd-s3-folder: "snapshots"
  data:
    - secretKey: application_key_id
      remoteRef:
        key: etcd-backblaze-secret
        property: application_key_id
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
    - secretKey: application_key
      remoteRef:
        key: etcd-backblaze-secret
        property: application_key
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        nullBytePolicy: Ignore
