---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: homepage-secret     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        services.yaml: |
          ---
          # For configuration options and examples, please see:
          # https://gethomepage.dev/en/configs/services

          - Line 0A:
              - Unifi:
                  icon: unifi
                  href: https://unifi.local.asztalos.net
                  widget:
                      type: unifi
                      url: https://unifi.local.asztalos.net
                      username: homepage
                      password: {{ .unifi_homepage_password }}

          - Line 0B:
              - UNVR-PRO:
                  icon: unifi
                  href: https://unvr-pro.local.asztalos.net
                  ping: https://unvr-pro.local.asztalos.net
              - Apprise:
                  icon: apprise
                  href: https://apprise.local.asztalos.net/cfg/apprise
                  siteMonitor: http://apprise.apprise.svc.cluster.local:8000
                  app: apprise
                  namespace: apprise

          - Line 0C:
              - FlexGet:
                  icon: flexget
                  href: https://flexget.local.asztalos.net
                  siteMonitor: http://flexget.flexget.svc.cluster.local:5050
                  app: flexget
                  namespace: flexget
              - ddns-updater:
                  icon: ddns-updater
                  href: https://ddns-updater.local.asztalos.net
                  siteMonitor: http://ddns-updater.ddns-updater.svc.cluster.local:8000
                  app: ddns-updater
                  namespace: ddns-updater

          - Line 1A:
              - ArgoCD:
                  icon: argo-cd
                  href: https://argocd.local.asztalos.net
                  siteMonitor: http://argocd-server.argocd.svc.cluster.local
                  app: argocd-server
                  namespace: argocd
                  widget:
                      type: argocd
                      url: http://argocd-server.argocd.svc.cluster.local
                      key: {{ .argocd_token }}

          - Line 1B:
              - Authentik:
                  icon: authentik
                  href: https://auth.local.asztalos.net
                  siteMonitor: http://authentik-server.authentik.svc.cluster.local
                  app: authentik
                  namespace: authentik
                  widget:
                    type: authentik
                    version: 2
                    url: http://authentik-server.authentik.svc.cluster.local
                    key: {{ .authentik_token }}

          - Line 1C:
              - Traefik:
                  icon: traefik
                  href: https://traefik.local.asztalos.net
                  siteMonitor: https://traefik.local.asztalos.net/api/overview
                  app: traefik
                  namespace: traefik
                  widget:
                      type: traefik
                      url: https://traefik.local.asztalos.net
                      username: red # optional
                      password: {{ .traefik_dashboard_auth }}

          - Line 1D:
              - Rancher:
                  icon: rancher
                  href: https://rancher.local.asztalos.net
                  siteMonitor: https://rancher.cattle-system.svc.cluster.local
                  podSelector:
                    app: rancher
                  namespace: cattle-system
              - Longhorn:
                  icon: longhorn
                  href: https://longhorn.local.asztalos.net
                  siteMonitor: http://longhorn-frontend.longhorn-system.svc.cluster.local
                  app: longhorn
                  namespace: longhorn-system

          - Line 2:
              - Uptime Kuma:
                  icon: uptime-kuma
                  href: https://uptime-kuma.local.asztalos.net/status/info
                  widget:
                      type: uptimekuma
                      url: https://uptime-kuma.local.asztalos.net
                      slug: info

              - Pi-Hole Raspberry Pi:
                  icon: pi-hole
                  href: https://pihole-rpi.local.asztalos.net/admin/
                  ping: https://pihole-rpi.local.asztalos.net/admin/
                  widget:
                      type: pihole
                      version: 6
                      url: https://pihole-rpi.local.asztalos.net
                      key: {{ .pihole_rpi_password }}

              - Pi-Hole Cluster:
                  icon: pi-hole
                  href: https://pihole.local.asztalos.net/admin/
                  siteMonitor: http://pihole-web.pihole.svc.cluster.local
                  app: pihole
                  namespace: pihole
                  widget:
                      type: pihole
                      version: 6
                      url: http://pihole-web.pihole.svc.cluster.local
                      key: {{ .pihole_cluster_password }}

              - Transmission:
          #        description: Torrent client
                  icon: transmission
                  href: http://transmission.local.asztalos.net:9091/transmission/web/
                  siteMonitor: http://transmission.local.asztalos.net:9091/transmission/web/
                  app: transmission
                  namespace: transmission
                  widget:
                      type: transmission
                      url: http://transmission-peer-tcp.transmission.svc.cluster.local:9091
                      username: {{ .transmission_username}}
                      password: {{ .transmission_password}}
                      rpcUrl: /transmission/ # Optional. Matches the value of "rpc-url" in your Transmission's settings.json file

              - Home Assistant:
                  icon: home-assistant
                  href: https://homeassistant.local.asztalos.net
                  widget:
                    type: homeassistant
                    url: https://homeassistant.local.asztalos.net
                    key: {{ .homeassistant_token }}
                    custom:
                      - state: sensor.outdoor_module_temperature
                        label: Temp
                      - state: alarm_control_panel.home
                      - state: binary_sensor.0x00158d000359f895_water_leak
                        label: Water leak
                      - state: sensor.solaredge_i1_ac_power
                        label: Solar power

          - Line 4:
              - Alloy:
                  icon: alloy
                  href: https://alloy.local.asztalos.net
                  siteMonitor: http://alloy.alloy.svc.cluster.local:12345
                  app: alloy
                  namespace: alloy

              - Prometheus:
          #        description: Metrics scraper
                  icon: prometheus
                  href: https://prometheus.local.asztalos.net
                  siteMonitor: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
                  app: prometheus
                  namespace: monitoring
                  widget:
                      type: prometheus
                      url: http://monitoring-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090

              - Grafana:
                  icon: grafana
                  href: https://grafana.local.asztalos.net
                  siteMonitor: http://monitoring-grafana.monitoring.svc.cluster.local/api/health
                  app: grafana
                  namespace: monitoring
                  widget:
                    type: grafana
                    url: http://monitoring-grafana.monitoring.svc.cluster.local
                    username: {{ .grafana_username }}
                    password: {{ .grafana_password }}

              - Paperless-ngx:
                  icon: paperless-ngx
                  href: https://paperless.local.asztalos.net
                  siteMonitor: http://paperless-ngx.paperless-ngx.svc.cluster.local:8000
                  app: paperless-ngx
                  namespace: paperless-ngx
                  widget:
                      type: paperlessngx
                      url: http://paperless-ngx.paperless-ngx.svc.cluster.local:8000
                      username: homepage
                      password: {{ .paperless_ngx_homepage_password }}

  data:
    - secretKey: traefik_dashboard_auth            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: traefik-dashboard-auth
        property: users  # 1Password item name
    - secretKey: homebridge_homepage_password            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homepage
        property: homebridge  # 1Password item name
    - secretKey: pihole_rpi_password            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homepage
        property: pihole-rpi  # 1Password item name
    - secretKey: pihole_cluster_password            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: pihole-secret
        property: webpassword
    - secretKey: transmission_username            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: transmission
        property: username
    - secretKey: transmission_password            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: transmission
        property: password
    - secretKey: grafana_username           # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana-secrets
        property: admin-user
    - secretKey: grafana_password           # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: grafana-secrets
        property: admin-password
    - secretKey: paperless_ngx_homepage_password            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homepage
        property: paperless-ngx  # 1Password item name
    - secretKey: unifi_homepage_password            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homepage
        property: unifi  # 1Password item name
    - secretKey: argocd_token            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homepage
        property: argocd  # 1Password item name
    - secretKey: authentik_token            # key in the Kubernetes Secret
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: authentik-blueprint-secrets
        property: authentik-homepage-token
    - secretKey: homeassistant_token
      remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        metadataPolicy: None
        key: homeassistant
        property: credential  # 1Password item name
