---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: homepage-env
    namespace: homepage
    env: homepage-config.env
  - name: homepage-config
    namespace: homepage
    files:
      - bookmarks.yaml=./config/bookmarks.yaml
      - kubernetes.yaml=./config/kubernetes.yaml
      - settings.yaml=./config/settings.yaml
      - widgets.yaml=./config/widgets.yaml
  - name: homepage-images
    namespace: homepage
    files:
      - custom_background.jpg=./images/custom_background.jpg
      - telekom.png=./images/telekom.png

resources:
  - homepage-secret.yaml
  - serviceaccount.yaml
  - rbac.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: homepage
    app.kubernetes.io/part-of: homepage
    app.kubernetes.io/instance: homepage
    app.kubernetes.io/component: homepage
