---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgresql-database.yaml
  - umami-postgres-secret.yaml
  - umami-app-secret.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

labels:
  - pairs:
      app.kubernetes.io/name: umami
      app.kubernetes.io/part-of: umami
      app.kubernetes.io/instance: umami
      app.kubernetes.io/component: umami
    includeSelectors: false
