---

- Misc 1:
  - Printer:
    - icon: printer
      href: http://printer.local.asztalos.net
      description: ""
  - NUT:
    - icon: nut
      href: http://raspberrypi.local.asztalos.net:8085/cgi-bin/nut/upsstats.cgi
      description: ""
  - rclone:
    - icon: rclone
      href: http://unvr-pro.local.asztalos.net:5572
      description: ""
