---
- logo:
    icon: homepage

- search:
    provider: duckduckgo # google, duckduckgo, bing, baidu, brave or custom
    focus: true # Optional, will set focus to the search bar on page load
    target: _blank # One of _self, _blank, _parent or _top

- kubernetes:
    cluster:
      # Shows cluster-wide statistics
      show: true
      # Shows the aggregate CPU stats
      cpu: true
      # Shows the aggregate memory stats
      memory: true
      # Shows a custom label
      showLabel: true
      label: "cluster"
    nodes:
      # Shows node-specific statistics
      show: true
      # Shows the CPU for each node
      cpu: true
      # Shows the memory for each node
      memory: true
      # Shows the label, which is always the node name
      showLabel: true

# - resources:
#    label: System
#    cpu: true
#    memory: true

#- resources:
#    label: Storage
#    disk: /mnt/storage

- openmeteo:
    label: Szentendre #optional
    latitude: 47.69
    longitude: 19.08
    timezone: Europe/Budapest # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits

- datetime:
    locale: hu
    text_size: md
    format:
        dateStyle: short
        timeStyle: short
        hourCycle: h23
