---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: tado-exporter-config
    namespace: tado-exporter
    env: tado-exporter-config.env

resources:
  - tado-exporter-secret.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - grafana-dashboard.yaml
