---
apiVersion: v1
kind: Service
metadata:
  name: tado-exporter
  namespace: tado-exporter
  labels:
    app: tado-exporter
    app.kubernetes.io/name: tado-exporter
    app.kubernetes.io/part-of: tado-exporter
    app.kubernetes.io/instance: tado-exporter
spec:
  selector:
    app: tado-exporter
  ports:
    - name: http
      protocol: TCP
      port: 9898
      targetPort: http
  type: ClusterIP
