---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tado-exporter-secret
  namespace: tado-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: tado-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        EXPORTER_USERNAME: "{{ .username }}"
        EXPORTER_PASSWORD: "{{ .password }}"
  data:
    - secretKey: username
      remoteRef:
        key: tado-exporter
        property: username
    - secretKey: password
      remoteRef:
        key: tado-exporter
        property: password
