---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: transmission
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      path: apps/transmission/install
  destination:
    server: https://kubernetes.default.svc
    namespace: transmission
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
