---
# apps/traefik/traefik-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.traefik.io/traefik
      chart: traefik
      targetRevision: 35.0.1
      helm:
        valueFiles:
          - $config/values.yaml
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      path: apps/traefik
      ref: config
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
