---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: flexget-secret
  namespace: flexget
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: flexget-secret
    creationPolicy: Owner
  data:
    - secretKey: config.yml
      remoteRef:
        key: flexget
        property: config.yml
    - secretKey: FG_WEBUI_PASSWORD
      remoteRef:
        key: flexget
        property: FG_WEBUI_PASSWORD

