---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: flexget-config
    namespace: flexget
    env: flexget-config.env

resources:
  - flexget-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml

generatorOptions:
  labels:
    app.kubernetes.io/name: flexget
    app.kubernetes.io/part-of: flexget
    app.kubernetes.io/instance: flexget
    app.kubernetes.io/component: flexget
