---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexget-config-pvc
  namespace: flexget
  labels:
    app: flexget
    app.kubernetes.io/name: flexget
    app.kubernetes.io/part-of: flexget
    app.kubernetes.io/instance: flexget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 200Mi
