---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flexget-config-pvc
  namespace: flexget
  labels:
    app: flexget
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 150Mi
