---
apiVersion: v1
kind: Service
metadata:
  name: flexget
  namespace: flexget
spec:
  selector:
    app: flexget
  ipFamilyPolicy: RequireDualStack
  ipFamilies:
    - IPv6
    - IPv4
  ports:
  - name: webui
    targetPort: 5050
    port: 5050
