---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: cloudflare-token-secret     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: cloudflare-token            # key in the Kubernetes Secret
      remoteRef:
        key: cloudflare-token-secret/cloudflare-token
