---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: kube-system
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "type": "bridge",
      "bridge": "br-iot",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "10.10.20.0/24", "gw": "10.10.20.1" }
        ]
      }
    }
