---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0.20",
      "mode": "bridge",
      "ipam": {
        "type": "host-local",
        "subnet": "10.10.20.0/24",
        "rangeStart": "10.10.20.13",
        "rangeEnd": "10.10.20.14",
        "routes": [
          { "dst": "10.10.20.0/24", "gw": "10.10.20.1"}
        ],
        "gateway": "10.10.20.1"
      }
    }
