---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0.20",
      "mode": "bridge",
      "ipam": {
        "type": "static",
        "routes": [
          { "dst": "10.0.20.0/24" }
        ],
        "gateway": "192.168.1.1"
      }
    }
