---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: multus-iot
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.3.1",
      "type": "macvlan",
      "master": "eth0.20",
      "mode": "bridge",
      "mac": "ce:ff:6a:78:88:a1",
      "ipam": {
        "type": "static",
        "addresses": [
          {
            "address": "10.10.20.13/24"
          }
        ],
        "routes": [
          {
            "dst": "10.10.20.0/24",
            "gw": "10.10.20.1"
          }
        ]
      }
    }
