---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homebridge-secret
  namespace: homebridge
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: homebridge-secret
    creationPolicy: Owner
  data:
    - secretKey: auth.json
      remoteRef:
        key: homebridge
        property: auth.json
