---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: homebridge-config
    namespace: homebridge
    env: homebridge-config.env

resources:
  - homebridge-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - ingressroute.yaml
