---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-config-pvc
  namespace: homebridge
  labels:
    app: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
