---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homebridge-config-pvc
  namespace: homebridge
  labels:
    app: homebridge
    app.kubernetes.io/name: homebridge
    app.kubernetes.io/part-of: homebridge
    app.kubernetes.io/instance: homebridge
    app.kubernetes.io/component: homebridge
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
