apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: technitium-dns-config
  namespace: technitium-dns
  labels:
    app: technitium-dns
    app.kubernetes.io/name: technitium-dns
    app.kubernetes.io/part-of: technitium-dns
    app.kubernetes.io/instance: technitium-dns
    app.kubernetes.io/component: technitium-dns
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 100Mi
