apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: technitium-dns
  namespace: technitium-dns  # or the namespace where your exporter runs
  labels:
    release: prometheus-operator  # match your Prometheus Operator’s selector if needed
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: technitium-dns  # or the label used by your exporter service
  endpoints:
    - path: /metrics
      interval: 30s
      targetPort: metrics
      honorLabels: true
  namespaceSelector:
    matchNames:
      - technitium-dns
