---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: local-asztalos-net
  namespace: cert-manager
spec:
  secretName: local-asztalos-net-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "default,traefik,authentik,monitoring,argocd,cattle-system,longhorn-system,pihole,apprise,ddns-updater,flexget,homebridge,netatmo-exporter,paperless-ngx,nut-exporter"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: "default,traefik,authentik,monitoring,argocd,cattle-system,longhorn-system,pihole,apprise,ddns-updater,flexget,homebridge,netatmo-exporter,paperless-ngx,nut-exporter"
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.local.asztalos.net"
  dnsNames:
  - "local.asztalos.net"
  - "*.local.asztalos.net"
