---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloudflare-token-secret
  namespace: cert-manager
spec:
  encryptedData:
    cloudflare-token: AgCl6jeUjCwBfNpIJYIM0wV1/tkYY8NpjtDZHxWLKDpX26jq3wMGq+OZ4qrICyuGAxhFqAB0KfPhyJwGmq6sOD5oKxJm4z0LrXZ9orlNsjSc4UjXhX/qDahomwSSyQNtT/rmMu8rsTAHrkVdcskO8RMJQTj1HuAHmfkoF5V/ZMJoiX36gAzJfjOdn0jfbOLjKIfnKFwue4prNxBpTyZ4nM9peS6xL1FmGhwnU4B8scu644SrDkARWjbHwK3pwTv6lQVtXj9njoOj0g7/VnfoFSXEQmbJd0fyx6VzK/8yGcwj65lpkQWFkfgwWAXxOAuqdh1FC8dt/ACSsPW0bVYj1+maEIkfcJDr1aHvJAt5G8O6/60UeFaRylIj+hvwnHiKYMZgoqGMfXX0oFvAw3Z4aOrDQHesYFLJ5UD3VVrobZbpk7k2vfkuxOko/C0dhYchzFEmtQXPA74g/0jIwd4m2Kz71V7QNfaYJg3fn7ARxnkamdCJOX7vEwyVkEE8UgWEkJHgDW9urFZXlh/npXGsiN6kfxS+DbO4DCthyqZMKV6JBdMlYuNX3mCGYAf10o+5MjIa0mq1ayxu/XB9s5XvHE26sPTysqXl97cowAs3eG9bXRGck4DokaZSOqwTRIgEfkxCUaCP1updyuwBn0qgxNrXF0RmqiTiMOo92qCiwbHBwLsbV2aqN/EC8MQsz4U/WfjGfnnQzxNRr3Hi9Md5sawTiJ9R26BmO499uKd9nNwUPx4T1OPRo+HF
  template:
    metadata:
      creationTimestamp: null
      name: cloudflare-token-secret
      namespace: cert-manager
    type: Opaque
