---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: authentik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`auth.local.asztalos.net`)
      priority: 10
      services:
        - name: authentik-server
          namespace: authentik
          port: 80
  tls:
    secretName: local-asztalos-net-tls
