{
 "title": "Raspberry Pi Dashboard",
 "description": "The dashboard presents metrics scraped by prometheus from a vcgencmd exporter implemented in Golang",
 "tags": [
  "raspberry pi",
  "prometheus",
  "vcgen-exporter"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "pmic_adc_metric", "query": { "query": "label_values(component)" } },
   {
    "name": "host",
    "query": {
     "query": "label_values({job=\"vcgen-exporter-metrics\"}, host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Raspberry pi", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "throttle state",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rpi_throttled{host=~\"${host}\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rpi_temp{host=~\"${host}\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "clock",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "rpi_clock{host=~\"${host}\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "pmic power",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rpi_pmic_adc{host=~\"${host}\", component=~\"${pmic_adc_metric}\", type=\"a\"} * ignoring(type) rpi_pmic_adc{host=~\"${host}\", component=~\"${pmic_adc_metric}\", type=\"v\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "rpi_volt{host=~\"${host}\"}",
     "legendFormat": "{{component}}"
    }
   ]
  }
 ]
}