---
apiVersion: traefik.io/v1alpha1 # traefik.containo.us/v1alpha1 depreciated in Traefik v3
kind: TraefikService
metadata:
  name: unifi
  namespace: traefik
spec:
  loadBalancer:
    servers:
      - url: "https://10.10.90.1"
    passHostHeader: true
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: unifi
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`unifi.local.asztalos.net`)
      kind: Rule
      middlewares:
        - name: default-headers
          namespace: traefik
        - name: https-redirectscheme
          namespace: traefik
      services:
        - name: unifi
          kind: TraefikService
  tls:
    secretName: local-asztalos-net-tls
