---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-sdk-store
  namespace: external-secrets
spec:
  provider:
    onepasswordSDK:
      vault: kubernetes
      auth:
        serviceAccountSecretRef:
          name: 1password-token
          key: token
        integrationInfo:
          name: "External Secrets Operator"
          version: v1
