---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-store
spec:
  provider:
    onepasswordSDK:
      vault: kubernetes
      auth:
        serviceAccountSecretRef:
          name: 1password-token
          key: token
          namespace: external-secrets
