---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-store
spec:
  provider:
    onepasswordSDK:
      vault: kubernetes
      auth:
        serviceAccountSecretRef:
          name: 1password-token
          key: token
          namespace: external-secrets
---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: onepassword-connect
spec:
  provider:
    onepassword:
      connectHost: http://onepassword-connect.onepassword.svc.cluster.local:8080
      vault:
        kubernetes: 1
      auth:
        serviceAccountSecretRef:
          name: 1password-connect-token
          key: token
          namespace: external-secrets
