---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: onepassword-cluster-store
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.1password-connect.svc.cluster.local
      vaults:
        my-vault: "vwdxu55eamsj6yljnkrwxfqv6q"
      auth:
        secretRef:
          connectTokenSecretRef:
            name: 1password-token
            key: token
