---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ddns-updater-env
  namespace: ddns-updater
data:
  TZ: "Europe/Budapest"
  PERIOD: "5m"
  UPDATE_COOLDOWN_PERIOD: "5m"
  PUBLICIP_FETCHERS: "all"
  PUBLICIP_HTTP_PROVIDERS: "all"
  PUBLICIPV4_HTTP_PROVIDERS: "all"
  PUBLICIPV6_HTTP_PROVIDERS: "all"
  PUBLICIP_DNS_PROVIDERS: "all"
  PUBLICIP_DNS_TIMEOUT: "3s"
  HTTP_TIMEOUT: "10s"
  LISTENING_PORT: "8000"
  ROOT_URL: "/"
  BACKUP_PERIOD: "0" # 0 to disable
  BACKUP_DIRECTORY: "/updater/data"
  CONFIG_FILEPATH: "/updater/config/config.json"
  LOG_LEVEL: "info"
  LOG_CALLER: "hidden"
  HEALTH_SERVER_ADDRESS: "0.0.0.0:9999"
  SHOUTRRR_ADDRESSES: "generic://apprise.apprise.svc.cluster.local:8000/notify/apprise?template=json&messagekey=body&disabletls=yes&tag=ddns&type=info&title=DDNS"
