---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: ddns-updater-secret
  namespace: ddns-updater
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: ddns-updater-secret     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        config.json: |
          {
            "settings": [
              {
                "provider": "cloudflare",
                "zone_identifier": "{{ .cloudflare_zone_id }}",
                "domain": "asztalos.net",
                "host": "@",
                "ttl": 600,
                "token": "{{ .cloudflare_token }}",
                "ip_version": "ipv4"
              }
            ]
          }
  data:
    - secretKey: cloudflare_zone_id            # key in the Kubernetes Secret
      remoteRef:
        key: cloudflare-token-secret/cloudflare-zone-id  # 1Password item name
    - secretKey: cloudflare_token            # key in the Kubernetes Secret
      remoteRef:
        key: cloudflare-token-secret/cloudflare-token  # 1Password item name

