apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ddns-updater-data
  namespace: ddns-updater
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Mi
