---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: daily-volume-backup
  namespace: longhorn-system
spec:
  name: daily-volume-backup
  cron: "0 2 * * *"
  task: "backup"
  groups: ["default"]
  retain: 3
  concurrency: 1
