apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: extra-filesystem-trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '0 18 * * *'  # Daily at 18:00
  groups:
    - temp
    - temp-1r
  name: extra-filesystem-trim
  retain: 0
  task: filesystem-trim
