apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: extra-filesystem-trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '0 1 * * *'  # Daily at 01:00 (before the daily backup job)
  groups:
    - temp
    - temp-1r
  name: extra-filesystem-trim
  retain: 0
  task: filesystem-trim
