apiVersion: v1
kind: LimitRange
metadata:
  name: longhorn-system-resource-limits
  namespace: longhorn-system
spec:
  limits:
  - type: Container
    max:
      cpu: "1"
      memory: 2Gi
    min:
      cpu: 100m
      memory: 128Mi
    default:
      cpu: 500m
      memory: 1500Mi
    defaultRequest:
      cpu: 100m
      memory: 256Mi
