---
# This StorageClass is used for frequently changing volumes where the content is not so important (Prometheus metrics, Pihole logs).
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-temp
provisioner: driver.longhorn.io
parameters:
  # Volume-specific snapshot settings
  snapshotMaxCount: "5"
  # Optionally set snapshot size limit
  snapshotMaxSize: "0"  # 0 disables size limit
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
