---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-volume-snapshot
  namespace: longhorn-system
spec:
  name: hourly-volume-snapshot
  cron: "30 */4 * * *"
  task: "snapshot"
  groups: ["default"]
  retain: 6
  concurrency: 1
