---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: hourly-volume-snapshot
  namespace: longhorn-system
spec:
  cron: "30 * * * *"
  task: "snapshot"
  groups: ["default"]
  retain: 24
  concurrency: 2
