apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: weekly-filesystem-trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: '0 5 * * 0'  # Weekly at 5 AM on Sundays
  groups: ["default"]
  labels: {}
  name: weekly-filesystem-trim
  retain: 0
  task: filesystem-trim
