---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default
  sources:
    - repoURL: 'https://github.com/gyulaasztalos/ArgoCD.git'
      targetRevision: main
      ref: config
    - repoURL: https://kube-vip.github.io/helm-charts
      chart: kube-vip
      targetRevision: 0.11.1
      helm:
        valueFiles:
          - $config/apps/kube-vip/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
