{
 "title": "Netatmo Weather Station for Prometheus",
 "description": "This dashboard is meant to be used with the Prometheus output from xperimental/netatmo-exporter\r\nhttps://github.com/xperimental/netatmo-exporter\r\nhttps://hub.docker.com/r/xperimental/netatmo-exporter",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "netatmo_sensor_temperature_celsius",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Relative humidity",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "humidity" }
   ],
   "targets": [
    {
     "expr": "netatmo_sensor_humidity_percent",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "CO2",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    { "expr": "netatmo_sensor_co2_ppm", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Atmospheric pressure",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "pressurembar" }
   ],
   "targets": [
    { "expr": "netatmo_sensor_pressure_mb", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Noise",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "dB" }
   ],
   "targets": [
    { "expr": "netatmo_sensor_noise_db", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "Rain amount",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "lengthmm" }
   ],
   "targets": [
    { "expr": "netatmo_sensor_rain_amount_mm", "legendFormat": "{{module}}" }
   ]
  },
  {
   "title": "RF signal strength",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "-netatmo_sensor_rf_signal_strength",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Wifi signal strength",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "dB" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "-netatmo_sensor_wifi_signal_strength",
     "legendFormat": "{{module}}"
    }
   ]
  },
  {
   "title": "Battery remaining life",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "netatmo_sensor_battery_percent", "legendFormat": "{{module}}" }
   ]
  }
 ]
}