---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: netatmo-exporter-config
    namespace: netatmo-exporter
    env: netatmo-exporter-config.env

resources:
  - netatmo-exporter-secret.yaml
  - pvc.yaml
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml
  - ingressroute.yaml
  - grafana-dashboard.yaml
