---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: netatmo-exporter-secret
  namespace: netatmo-exporter
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect
    kind: ClusterSecretStore
  target:
    name: netatmo-exporter-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        NETATMO_CLIENT_ID: "{{ .client_id }}"
        NETATMO_CLIENT_SECRET: "{{ .client_secret }}"
        netatmo-token.json: |
          {
            "access_token":"{{ .access_token }}",
            "refresh_token":"{{ .refresh_token }}",
            "expiry":"2025-07-30T10:50:59.589899665Z"}
          }
  data:
    - secretKey: client_id
      remoteRef:
        key: netatmo-exporter
        property: client_id
    - secretKey: client_secret
      remoteRef:
        key: netatmo-exporter
        property: client_secret
    - secretKey: access_token
      remoteRef:
        key: netatmo-exporter
        property: access_token
    - secretKey: refresh_token
      remoteRef:
        key: netatmo-exporter
        property: refresh_token
