---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netatmo-exporter-config-pvc
  namespace: netatmo-exporter
  labels:
    app: netatmo-exporter
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Mi
