---
apiVersion: v1
kind: Service
metadata:
  name: netatmo-exporter
  namespace: netatmo-exporter
  labels:
    app: netatmo-exporter
spec:
  selector:
    app: netatmo-exporter
  ports:
    - name: metrics
      protocol: TCP
      port: 9210
      targetPort: metrics
  type: ClusterIP
