---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-blueprint-secrets
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: authentik-blueprint-secrets    # name of the Kubernetes Secret to be created
    creationPolicy: Owner
    template:
      engineVersion: v2
      type: Opaque
      data:
        oauth-providers.yaml: |
          version: 1
          metadata:
            name: "Oauth Provider Blueprint"
          entries:
            - model: authentik_providers_oauth2.oauth2provider
              state: present
              identifiers:
                name: rancher-oauth-provider
              attrs:
                client_id: rancher
                client_secret: {{ .rancher_client_secret }}
                signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
                property_mappings:
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
                   - !Find [authentik_providers_oauth2.scopemapping, [scope_name, offline_access]]
                authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
                authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
                invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
                redirect_uris:
                  - matching_mode: strict
                    url: https://rancher.local.asztalos.net/verify-auth
            - model: authentik_providers_oauth2.oauth2provider
              state: present
              identifiers:
                name: paperless-oauth-provider
              attrs:
                client_id: paperless
                client_secret: {{ .paperless_client_secret }}
                signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
                property_mappings:
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, offline_access]]
                authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
                authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
                invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
                redirect_uris:
                  - matching_mode: strict
                    url: https://paperless.local.asztalos.net/accounts/oidc/authentik/login/callback/
            - model: authentik_providers_oauth2.oauth2provider
              state: present
              identifiers:
                name: grafana-oauth-provider
              attrs:
                client_id: grafana
                client_secret: {{ .grafana_client_secret }}
                signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
                property_mappings:
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, offline_access]]
                authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
                authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
                invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
                redirect_uris:
                  - matching_mode: strict
                    url: https://grafana.local.asztalos.net/login/generic_oauth
            - model: authentik_providers_oauth2.oauth2provider
              state: present
              identifiers:
                name: argocd-oauth-provider
              attrs:
                client_id: argocd
                client_secret: {{ .argocd_client_secret }}
                signing_key: !Find [authentik_crypto.certificatekeypair, [name, authentik Self-signed Certificate]]
                property_mappings:
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, openid]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, email]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, profile]]
                  - !Find [authentik_providers_oauth2.scopemapping, [scope_name, offline_access]]
                authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
                authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
                invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
                redirect_uris:
                  - matching_mode: strict
                    url: https://argocd.local.asztalos.net/api/dex/callback
        users.yaml: |
          version: 1
          metadata:
            name: "Users Blueprint"
          entries:
            - model: authentik_core.user
              state: present
              identifiers:
                username: akadmin
              attrs:
                name: Admin User
                password: {{ .akadmin_password }}
                email: {{ .akadmin_email }}
                is_active: true
                is_superuser: true
            - model: authentik_core.user
              state: present
              identifiers:
                username: Gyula
              attrs:
                name: Gyula
                password: {{ .gyula_password }}
                email: {{ .gyula_email }}
                is_active: true
                is_superuser: true
            - model: authentik_core.user
              state: present
              identifiers:
                username: Anita
              attrs:
                name: Anita
                password: {{ .anita_password }}
                email: {{ .anita_email }}
                is_active: true
                is_superuser: false
            - model: authentik_core.user
              state: present
              id: homepage
              identifiers:
                username: homepage
              attrs:
                name: Homepage User
                password: {{ .homepage_password }}  # Must provide a password
                email: {{ .homepage_email }}
                is_active: true
                is_superuser: false
                permissions:
                  - authentik_core.view_user     # Can view User
                  - authentik_events.view_event  # Can view Event
            - model: authentik_core.token
              state: present
              identifiers:
                identifier: homepage-token
              attrs:
                key: {{ .homepage_token }}  # Set a strong secret value here
                user: !KeyOf homepage
                intent: api
                expiring: false

  data:
    - secretKey: rancher_client_secret                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-rancher-client-secret    # 1Password item name
    - secretKey: paperless_client_secret                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-paperless-client-secret
    - secretKey: grafana_client_secret                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-grafana-client-secret
    - secretKey: argocd_client_secret                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-argocd-client-secret
    - secretKey: akadmin_password                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-akadmin-password
    - secretKey: akadmin_email                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-akadmin-email
    - secretKey: gyula_password                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-gyula-password
    - secretKey: gyula_email                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-gyula-email
    - secretKey: anita_password                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-anita-password
    - secretKey: anita_email                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-anita-email
    - secretKey: homepage_password                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-homepage-password
    - secretKey: homepage_email                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-homepage-email
    - secretKey: homepage_token                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-secrets
        property: authentik-homepage-token
