apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-meta
  namespace: authentik
data:
  meta-blueprint.yaml: |
    - model: authentik_core.meta
      state: present
      identifiers:
        name: meta-blueprint
      attrs:
        blueprints:
          - users.yaml
          - groups.yaml
          - forward-auth.yaml
          - oauth-providers.yaml
          - applications.yaml
