---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-redis-credentials
  namespace: authentik
spec:
  encryptedData:
    redis-password: AgBwfcu3ej+CjhAAntZeBpU/E84rrsfD1bZjZgJuMYlD1jVnQnlrvuUv/kHzc6FuLWCthIO/Ls1RK40byFYd5WGRVHtPasf7VehGn2W5q03mWVIhdtiTBs2b6IYqPv2q4+vjBYgT85jNN/jmQWvM5ppH8Q2Tqg5h3/LQ+YKRkmY+HOfVjB/rrox8R+Zkx2YuCD9sLtUBnIZV/SmiXBEzJRySzJa/tyJElRB7UvNel73wr35p+D0/QoFiDbyFsfmq0FnQQSqsh9Qbpeyb0ak0Vdz++RyJqfM7uVojWuuXx4clSjRdPVGsvT+uR7DKN4zgqfQ2lYUg+Qemaa6KFbIqpovmotAgu+oeTjM3sv6xX9PhEwx4jE9R1Lzy/9rKYBv9OAwq3nwEndt2ZNIEjFGaiunT2bQNcq2dgGk+Gv5VKiZyd43e50oDZJtVqfhAXQ1ZmoHb3yuoztqkNERXcFgIu3tfmEag+2dcnkbPcUq27T1rBE5eEv9N8AnAQWTMVcTGHdezVDpRwdwX9CIHqFIuwU3O3V8bcH1B6IWjeB8T9SAzXUZPNhsc/pVTjD0mjBEl1oQCWiPlY2jpYCWxcCgC9QTa9BF/U2zUc6k3c3Uq//LXpNgkmHL1BOEcWu1aD7JfrC9dIoOZBcNQiWDHPDdohJmV4CkuTIDW0TME4ZBzR9MSf+1oYF6ONcg9MpjjcAk1OqGJuSVG6WKvNf/kFQp2T3llIS2rMLViluXpZsmPEAKfQQ1tmj3Rzz/l
  template:
    metadata:
      creationTimestamp: null
      name: authentik-redis-credentials
      namespace: authentik
