apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-applications
  namespace: authentik
data:
  applications.yaml: |
    version: 1
    metadata:
      name: "Applications Blueprint"
    resources:
      - model: authentik_core.application
        state: present
        identifiers:
          slug: paperless
        attrs:
          name: Paperless-ngx
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, paperless-oauth-provider]]
          icon: https://paperless.local.asztalos.net/favicon.ico
      - model: authentik_core.application
        state: present
        identifiers:
          slug: grafana
        attrs:
          name: Grafana
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, grafana-oauth-provider]]
          icon: https://grafana.local.asztalos.net/public/img/fav32.png
      - model: authentik_core.application
        id: traefik_forward_auth_app
        state: present
        identifiers:
          slug: traefik-forward-auth
        attrs:
          name: "Traefik Forward Auth"
          provider: !Find [authentik_providers_proxy.proxyprovider, [name, traefik-forward-auth]]
          icon: https://traefik.local.asztalos.net/dashboard/icons/favicon-32x32.png
      - model: authentik_outposts.outpost
        id: embedded_outpost
        lookup: name:"authentik Embedded Outpost"
        operations:
          - op: add
            path: /applications
            value:
              - ref: traefik_forward_auth_app
