---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-applications
  namespace: authentik
data:
  applications.yaml: |
    version: 1
    metadata:
      name: "Applications Blueprint"
    entries:
      - model: authentik_core.application
        state: present
        identifiers:
          slug: rancher
        attrs:
          name: Rancher
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, rancher-oauth-provider]]
          policy_engine_mode: any
          meta_launch_url: "https://rancher.local.asztalos.net"
          icon: https://rancher.local.asztalos.net/favicon.png
      - model: authentik_core.application
        state: present
        identifiers:
          slug: paperless
        attrs:
          name: Paperless-ngx
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, paperless-oauth-provider]]
          policy_engine_mode: any
          meta_launch_url: "https://paperless.local.asztalos.net"
          icon: https://paperless.local.asztalos.net/favicon.ico
      - model: authentik_core.application
        state: present
        identifiers:
          slug: grafana
        attrs:
          name: Grafana
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, grafana-oauth-provider]]
          policy_engine_mode: any
          meta_launch_url: "https://grafana.local.asztalos.net"
          icon: https://grafana.local.asztalos.net/public/img/fav32.png
      - model: authentik_core.application
        state: present
        identifiers:
          slug: traefik-forward-auth
        attrs:
          name: "Traefik Forward Auth"
          provider: !Find [authentik_providers_proxy.proxyprovider, [name, traefik-forward-auth]]
          policy_engine_mode: any
          meta_launch_url: "https://traefik.local.asztalos.net"
          icon: https://traefik.local.asztalos.net/dashboard/icons/favicon-32x32.png
      - model: authentik_core.application
        state: present
        identifiers:
          slug: argocd
        attrs:
          name: ArgoCD
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, argocd-oauth-provider]]
          policy_engine_mode: any
          meta_launch_url: "https://argocd.local.asztalos.net"
          icon: https://argocd.local.asztalos.net/assets/favicon/favicon-32x32.png
