---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-blueprint-forward-auth
  namespace: authentik
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: authentik-blueprint-forward-auth     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: forward-auth.yaml                # key in the Kubernetes Secret
      remoteRef:
        key: authentik-blueprint-forward-auth/forward-auth.yaml    # 1Password item name
