apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-applications
  namespace: authentik
data:
  applications.yaml: |
    version: 1
    metadata:
      name: "Applications Blueprint"
    entries:
      - model: authentik_core.application
        state: present
        identifiers:
          slug: paperless
        attrs:
          name: Paperless-ngx
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, paperless-oauth-provider]]
          icon: https://paperless.local.asztalos.net/favicon.ico
      - model: authentik_core.application
        state: present
        identifiers:
          slug: grafana
        attrs:
          name: Grafana
          provider: !Find [authentik_providers_oauth2.oauth2provider, [name, grafana-oauth-provider]]
          icon: https://grafana.local.asztalos.net/favicon.ico
