---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-blueprint-forward-auth
  namespace: authentik
spec:
  encryptedData:
    forward-auth.yaml: AgBs/BkhSj/rAXCwe0JnyY4e7vz3vmUjvLIa7Q1nsk6E2S52CFPO/ukKN6bEOIY3jZ6peuYTr8041MDD37JNQG5arestpRFjwTeDD/wGdeZWUioI3aXDU5GfxnqA2XYykSEA0w0KYHIxD3J8HswZHiKc7jHJSQApLjNocEboS5CRnB5BcHXieqDWgI0a47FpMlkm8XzusEbsHRiX30jzprwODWpM/06CMrwbQzsG9eerbGgebC3i1KTroMgw20yDo8re5BBkFTjgV9r5VaOgkzlh9VOYuRKvuOjbUC6b90oP8grVrgJM8kuPV3zMUoCcpGmASzjzOQhxYbMgLL3VQ1aI67n35rHLJ2cMcTVXaxc8uexl3pROE/fvWT4b2O76va6IslJBOxpsA+QdGM9Lnfb3x9JGO/V9cDscpwv2f4IAc7QGEMnsvTfQZ6p+mvL0eC3lpEyjbQZJdydAplTCC/mIlA2cWcCOmcZIppVMRV4AtO4WoyQpOjScb0yGCtQIpd3uIxmsxnLzyLpOr1Ew0Y7w8oRZ57CArs/+6VjvBl0HaJJaQrQMzzkq7sipsBl7/ms/VZ3Y1JpdHf6CLSygIDhd7TfNV6WBqG7oCkNY0MQEkEUgD6OQ9I1rJTupq+u9XmZIygH6Pb4vwmBdWBU/RsCgQt+veK6wmrfDMgnH2lWEhsRakOIeaXXY5Qictv2Y4+8Dg9ygbUgO4kOWgV0HzNv7CnC7paQfrSBll8JfKjdUijZpMkT1/6o5AHWTShP7AQvsYchX6CY/7ND75QbqlX+Z4L8eQeczU5Oa06XTe1Lk1tRsSufooE0kGd4wkOK8OdRfKKWxKH4caBahffSpYciU2MrpXJsZtkDno6xCYVP0At0eGuEOcIPtm+rVcZpveGpUSrhRVVLHwo4K/czx5YsfRtIft7hQJ3r4B5l1ZcIiLbYxwLeAqyyeXzKJDWSCs0tIYSqGsfgF428Cw6X+TrLYDZz4o/C3/aI79zpldqCQWRvzpgsMc0BuS5k4ZXeIrhRMXarYvFAsY12euVs8ju43G1LWShVMQEMvYOeqmEMbFwXIbEMIUb9q/9JQzBPWmAic3bTL4Z/YTuvkgbP4LcskDfmVXGCKz3ofny/jTLn0APwatT8OXbjg2s57EvcGRKZJl5oSCq8flWAAOqzomU7Z6jS1WLlqjn/rgttxyP1SxtN/56B0qmHE4y+gi9J+vAx7KnY6DS0gmNBSbCsiEOlO3C7hKBrg6mXC81C6GK724sV/wooz3S1orjrS5JUodS+OTVDsSdMAKQZQsM5+DEff8yjbMwQj42hr2QbpUwpE2akQBLp0kXlHs341EhW7VrOGMP3vFdR0apno5IbmpfVjuxg9J25fm6q3WcJRF6XSovigVWa6xbg=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-blueprint-forward-auth
      namespace: authentik
