apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-forward-auth
  namespace: authentik
data:
  forward-auth.yaml: |
    version: 1
    metadata:
      name: "Forward Auth Provider Blueprint"
    resources:
      - model: authentik_providers_proxy.proxyprovider
        state: present
        identifiers:
          name: traefik-forward-auth
        attrs:
          mode: forward_domain
          external_host: https://auth.local.asztalos.net
          authorization_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
          invalidation_flow: !Find [authentik_flows.flow, [slug, default-invalidation-flow]]
          cookie_domain: local.asztalos.net
