---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-outpost
  namespace: authentik
data:
  outpost.yaml: |
    version: 1
    metadata:
      name: "Authentik Embedded Outpost Blueprint"
    entries:
      - model: authentik_outposts.outpost
        identifiers:
          name: "authentik Embedded Outpost"
        attrs:
          applications:
            - !Find [authentik_core.application, [name, Traefik Forward Auth]]
          config:
            kubernetes_ingress_annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
            log_level: info
            docker_labels: null
            authentik_host: https://auth.local.asztalos.net
            docker_network: null
            container_image: null
            docker_map_ports: true
            refresh_interval: minutes=5
            kubernetes_replicas: 1
            kubernetes_namespace: authentik
            authentik_host_browser: ""
            object_naming_template: ak-outpost-%(name)s
            authentik_host_insecure: false
            kubernetes_json_patches: null
            kubernetes_service_type: ClusterIP
            kubernetes_image_pull_secrets: []
            kubernetes_ingress_class_name: null
            kubernetes_disabled_components: []
            kubernetes_ingress_secret_name: authentik-outpost-tls
            kubernetes_httproute_annotations: {}
            kubernetes_httproute_parent_refs: []
