---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-credentials
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword-connect           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: authentik-credentials     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: bootstrap-password             # key in the Kubernetes Secret
      remoteRef:
        key: authentik-credentials
        property: bootstrap-password   # 1Password item name
    - secretKey: bootstrap-token              # key in the Kubernetes Secret
      remoteRef:
        key: authentik-credentials
        property: bootstrap-token
    - secretKey: postgresql-password              # key in the Kubernetes Secret
      remoteRef:
        key: authentik-credentials
        property: postgresql-password
    - secretKey: redis-password               # key in the Kubernetes Secret
      remoteRef:
        key: authentik-credentials
        property: redis-password
    - secretKey: secret-key                  # key in the Kubernetes Secret
      remoteRef:
        key: authentik-credentials
        property: secret-key
