---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-redis-credentials
  namespace: authentik
spec:
  encryptedData:
    url: AgA8YSB01nksnLlLWiLimEAdP/XhCNAg8RW+eZh6gHblbA4rxb8xgCXfggAl5wp9SHdOPKRCBpXUb8KTWFsIR4LI5HEsW8RRGrm7oj+MPhEVh8s+6ejPrq+unUDwfXVouWQPi2CvjkML6l57QqWk8nBYz0osB7TxnEpePyGmbIr5JeobTaIBSbAqRs9dUq/HB/GglmLvgiFYFL7dh5hfZ5ZInCC0Lj4RM+jbcfb4m4HdQ7ALabCIwqj9F6ADudKaV0DcgAvMqrofJcBUFppttSZd+plNqTfLD6+9niccOOXUBWDJdCIKlArXuaY2puB2bwLiLULB8gtbZIUGeuctzlUVsOozTrlpt5IIRynVH4u1lyPRKHcmzbdDeBXLuB5IbxSH54/vbPc2bEZevwgPEzZEuYVLtCUVpTCH1TmzWNuO1eI2Wd9b/v0XnQBwUbbIMF2/uACIQQnalYyllXZDBDYGV+6JrQw4DJP+RreShCSSsXD9z6k7alj0OoteGeqIafHzki7G/3cpUgTUvac8U9slmnjiSTvNiI8cfFJSlhZGrqrAw+IcMFX+drJXSMy51NjxpoRRG96FYykvhKDWHme0HDxiUD1W4xDRvJkGypl6yMyPWILNirAkJLrPB25iCZyehY+99Xhcica/Kv2T9G5zaTSrhI6bIoCxX+JOD63xw44zKsSDWm+/7sENFFCWgxpgYlcb2Zthf3kxFiuOKCqU1YtFK+p0Rw0edW+A/sk7UFf3MHWwjwnIpB5nILccqWEe/44pzJtRzKq+kJsnwcfkDbONB5zNEVPnmtxXGScuPMQFvfOiFbjeKXwluHHrGlM0/tLdZM8=
  template:
    metadata:
      creationTimestamp: null
      name: authentik-redis-credentials
      namespace: authentik
