---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentic-blueprint-secrets
  namespace: authentik
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: authentik-blueprint-secrets    # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: forward-auth.yaml                # key in the Kubernetes Secret
      remoteRef:
        key: authentic-blueprint-secrets/forward-auth.yaml    # 1Password item name
    - secretKey: oauth-providers.yaml                # key in the Kubernetes Secret
      remoteRef:
        key: authentic-blueprint-secrets/oauth-providers.yaml
    - secretKey: users.yaml                # key in the Kubernetes Secret
      remoteRef:
        key: authentic-blueprint-secrets/users.yaml
