---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-blueprint-forward-auth
  namespace: authentik
spec:
  encryptedData:
    forward-auth.yaml: AgBn1QmZB/fkHaVixMFDuM2tBMKg6cX7M17DgBIOh6zI5M/kSHSO7R8F1QpFYIGEFYFZk8QFLNTMSLiauhWn7lY6M47Mk5wQfxr7b8lgRfrReXTJlj60IZAvqkC+bwZTZFQ3s+oIsoAVr9B+9m/jm2tyBhR8HMxCNafSK2LU33AZ3lzfT+Cu7B+U4oLiguyoZen0byM8FdrZqjgmL1w5C0tsu5H05S20G+L/3/kNvXeptVGiE9lmRY5lxkGqblIc0EKXflYxnTsSCSZx4Yo5f6DPO+DizRwPZsf5jCCR9FeIC7aTnIo6MOklVP/K0PYKL1BZINUbFf13p7M9wi+5v3RfbCa4sXraiV7TAEym7zqQLHNFpL5nUmHhF2c9aEJfytf+R0GP/Rno5y2skyVRwdrK5kB1GcTJkvm0yHOqN7HbRQsP2Myvm0V+Kbk4Zs+RkaE64IVg91wVDBkQZS2cairKXQloffrHAn2Zr7vZENkBhHdZY3DgZMFfpn0pYG1zk3zr9E7CjsKaRJhOwq+iNJIPXHR6aZgw7GsOQxK4knageqnsIzMwlaeWpPUeyP9+kEgGT9WpOJwaUNAluLJPTvIKpawiVHtrdXBHcCDNfdmtPBu33acmUVDNICrlb24AACPP5AsTpGNVMlU/IhJWarbHihR3o0zzb6Ue2QygIJg+cuUPEWFa14LMwd0yXJnM/VFaWC7PEVIuXMyATU7/dJfdN20a0va8TZahas2mS7rvxPTaI060rtXgVhQ7HIC8UWv/0m5CPSEvd+JOTBQKYoniDuH38Fq2dK34qJBj1xdkCx7GjgqrHc5VX2Jul9E5nrticiiNF+l3sJKkCUtoYmpZlQSQncX1IcW5IZ2oMPZ6y3kRBya1MnAnRQhYwxZjsQG8JWM5oRQUD0DIvJXG2Mr9vRvZXsscysSmYRQBvyH0Uh9LO+1JO0gfUdXWC63w7/VUNluUUG8P8x4TZz1ylsLKge2pQ/HjnsQ+3Y1FmIe30+Fm+yoFpRo5hwt2X/wm3OZSK+B8gegQXJt86k/u9tni5n018pwpGnKQAsGfbNduxFsQJsQ/3KF2DffB2jrn5JS3poH1qOgh3hRA6SFw8GuTLelTYefZaKV7vGT3N11lqmH8Aur+4ngq0qPR1yizcEzct3sANxMf+HR+d7so0bCfrieKdtqx/bAXExP2I/fqw4B8vjNH3Qd0fweZ+LLOtM5psOInPp3dMXyiSZBwecsVIbLHO3WjcXWDfp+Y2YOGjiar9Xgs4ejomVRbo3t3/sf/qVYGNos+orhKSqp3V0VHvVkUDKH6B9R535BTxzGFT4OmfxqGf+EzhvaCJ1NrFeHvY+U5Ay/Hd9emOH952lFw3aqq6NnGnXTK+SJL3TIOFdcSJGBW
  template:
    metadata:
      creationTimestamp: null
      name: authentik-blueprint-forward-auth
      namespace: authentik
