---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-outpost
  namespace: authentik
data:
  outpost.yaml: |
    version: 1
    metadata:
      name: "Authentik Embedded Outpost Blueprint"
    entries:
      - model: authentik_outposts.outpost
        identifiers:
          name: "authentik Embedded Outpost"
        attrs:
          providers:
            - !Find [authentik_providers_proxy.proxyprovider, [name, traefik-forward-auth]]
          config:
            kubernetes_httproute_annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
