---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-blueprint-forward-auth
  namespace: authentik
spec:
  encryptedData:
    forward-auth.yaml: AgAf0BrfwShKZsqguudtbG1Zviy4kCV/iVhqASt48BTrXb9UfDIcpJ2M7y9TJ4kOH+3wSMp6SDRWcZHidEgJz6wt8ViTn0Scgy5rzK+42NvqhAUPXmBXypyrrvuVKIHzy0q8PVv3kMHUevEiRXo+cqn2Dhy6AQ6MoV/oqaANrVS/6oY3xnld9Ha2+IP7uHTg1eql4CIQ2HQuJgNv3KE1epPCxciwDnDC0WzIfuOmw2yzBSRomF5BQbM+JpBvMaRm+1hoerE/XBFbJiJ6dpIYzjjPoGAomy7AMs3jDHMIGvrwXYkTQ64TOTQPuhGCqod8QCCdtsdofU4ZHYJkg95E6AAgaDhUWjuXaCsJXKIwc6DoN/wZefcxh/2XXWSwZ+rmD6Pf5H0VMuwKaGWZeiOuyT7pRwynEeIUISYl0dMIMG9DyGfFhf5oovV+T9Wvsmlw0B9Bm6oRc6mJr+SySGYJv5WcUeMoV3no9OdT4pkadUMHrXo93EBI7IC1U0X4wDIvoQ9E2Hj6ihg9YGGCkF/+ffsGI1s/xzG6FYmyrUcbEQbK1bm7uJ1H+u0q1HrkryjFnzep+P2D3MyUQBWjhCjgs9IDxOuOBKiu0qMnwZ1YOZZwL1wItA6mb4rMT5p6dMKiQV+KrL7EXItv6CQ9Kf1DEe344L6UO7x9Bias/Lj8T/2V8En9/X0+0o+6TGou8LaB+6G++T+m8xt7+T8DXhsAwGJIAk9YjswInYS3ypuYAc4fw/rGJS5vh0gxJE4FDoJQavd1ULTUlU8OSTv2RaGxTVq4dfRUuXzPs3Jz5Mbebyv8juu9yw1uLzoUD8m+xxm6liCmKnaO9NvAG0YSDZlMGVjsfzJS0yTP9fXih4ETBEBuI3FFmH4qLa/RGs9D+vA9bP+3GN/8LLVnB8QoaMVnM+JFR5tiA6VyZZDRCUA+84SIw0smDKIeH7+dVypnVzJ8qRX/kj9LdVKuoPao3cBtmrm5sihFc6PfWzVOYiETHWx007YR4Zwzf0VMiHuTlB29y23li/yeCEq8L++g8VO5ypdmHl69NJlgBRKFlHxo5g51uoCfUuM3u6ZydyWSNNaZj1adqpIw3SOnxeCoAZQNDZOy4DBcggvWBpNom7WNtFjJFtC/iLFAbcpFAtiP5s7OrInH3yH3QnAqFYi9BgRqEbDeaZQ9pWpO82fTcYlopWSpmum5Aad08Zwt7v+Il27PRHnLYbS669UAJybzVrlop8Xy8yGAr2MXCpWm2haN/HPInUBCGi0BKtKrI8j5srHJ+v7/hoqsvzphChBNtyFnk31HJVJkYsS9JkoE0zsZd9DqmFMNtQeOFG8MKZSu4S7iyFIf1NWNHEHd+gwvXmmH5sdEihcyUzs8yJ6zzxQXhh1+LKwhFLszL2v6JQ==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-blueprint-forward-auth
      namespace: authentik
