---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-groups
  namespace: authentik
data:
  groups.yaml: |
    version: 1
    metadata:
      name: "Groups Blueprint"
    resources:
      - model: authentik_core.group
        state: present
        identifiers:
          name: powerusers
        attrs:
          users:
            - !Find [authentik_core.user, [username, Gyula]]
      - model: authentik_core.group
        state: present
        identifiers:
          name: standardusers
        attrs:
          users:
            - !Find [authentik_core.user, [username, Anita]]
