---
apiVersion: v1
kind: ConfigMap
metadata:
  name: authentik-blueprint-applications
  namespace: authentik
data:
  applications.yaml: |
    version: 1
    metadata:
      name: "Applications Blueprint"
    resources:
      - model: authentik_core.application
        state: present
        identifiers:
          slug: paperless
        attrs:
          name: Paperless-ngx
          provider: !KeyOf paperless-oauth-provider
          policy_engine_mode: any
          meta_launch_url: "https://paperless.local.asztalos.net"
          icon: https://paperless.local.asztalos.net/favicon.ico
      - model: authentik_core.application
        state: present
        identifiers:
          slug: grafana
        attrs:
          name: Grafana
          provider: !KeyOf grafana-oauth-provider
          policy_engine_mode: any
          meta_launch_url: "https://grafana.local.asztalos.net"
          icon: https://grafana.local.asztalos.net/public/img/fav32.png
      - model: authentik_core.application
        state: present
        identifiers:
          slug: traefik-forward-auth
        attrs:
          name: "Traefik Forward Auth"
          provider: !KeyOf traefik-forward-auth
          policy_engine_mode: any
          meta_launch_url: "https://traefik.local.asztalos.net"
          icon: https://traefik.local.asztalos.net/dashboard/icons/favicon-32x32.png
      - model: authentik_core.application
        state: present
        identifiers:
          slug: argocd
        attrs:
          name: ArgoCD
          provider: !KeyOf argocd-oauth-provider
          policy_engine_mode: any
          meta_launch_url: "https://argocd.local.asztalos.net"
          icon: https://argocd.local.asztalos.net/assets/favicon/favicon-32x32.png
