---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-redis-credentials
  namespace: authentik
spec:
  refreshInterval: 4h
  secretStoreRef:
    name: onepassword-store           # your ClusterSecretStore name
    kind: ClusterSecretStore
  target:
    name: authentik-redis-credentials     # name of the Kubernetes Secret to be created
    creationPolicy: Owner
  data:
    - secretKey: redis-password               # key in the Kubernetes Secret
      remoteRef:
        key: authentik-credentials/redis-password  # 1Password item name
