---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-email-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgCjRcOXPofLPIVz6C/SW+1IN5qwJXiP8UHBfUy+y7VwU+LiNDzjXsFpEO5Wm8N6qpkAUGypfZ+HEMs+0+PyZEl09EUUDJ/YQsIlyP30O4j7GikrYRftl8C7Te7+EkxxFtVzgGQoJlMhGUm0tRBNM9NqNaHFUJkMv6b0AE3NjJVzEGy8ZMkI8MH7zZuEcsgXM1bEQidx57hW9XaK02NDfKYERhRH2Uin/jf3QHQeRFVaQgxkY+qxBZfcsMsTmsx278kVH7Nd59ZH+TBMbFkVU4KTK9ti4Nta2cdELIGYZeQxS2D/wP5dPso43OOjlJ6Vjv07Fp/ON1j8BclqS9akLJJG/VN87+4Om6iWvzUt9DwQhQT5uovLXuctxMQZSWIV/Y4GqI1AoFGBKIY1FlK1qzKon+TXGHk4vdgzf57zW7/RHUSZhmm5LCPa9YR1Q77sGNDRPBkRFyx5Ui/Dz36OfFSg9reRlPEeuteaQCePI0+2SQfCmdiCCYyWO3LuN4CkCkECThsyxXB9iRrqfQYGeC8KQsqABabrT7U3lG18zljH33M9+2MteZKqZqmTZjuNKBiCGMwMCJHTUiSqV4IWrsY24BsvcKnoo0pZV0Vhr0NwNmWs3soXGM/gp7+91JrYBA2hczSH2ut4L9AQqpS0IA7xs3oVvJbyUHHhAEo59hGUjiEARB/ISr8TbKo1CYX0BRuGE8TqMk1PvzTIpTWEMSADTdjX
    username: AgAmfrKYL+1LPl5+BtJf6cJDrJRWaJfR5ny12CcDelklSkWzDlgOz4fZn8UMkQQIK+y6HHHEsX8YGC7t68LmO5YOCN76zu7tVJJa62e7wpLveWiWd6vN4QuCYEmA7QWqREJn96gFkAQ7v8Nb7I+e1tVuQpAyS0asNXe1uh2adNChHO8wnzGNUDg2U6uhv4flV1wmxE0htV9m+gTIqNIX5cVuyrKXrTXCDVG7zaPPzAhyYj9JYqMTZ7CVT0KnG/gQ07tKNz3UW3VvHt3MBwYhi8qatob/j21q/IONIAwHcRURvc/bmwcxRSgKY+efQ7Di6LGPQjnMwssPt1nh3s0T+6We800Q0z3a/16XxYiBfYMPpNC/EjeBw3ksNgUdzl2P8kNRo8mOyYXnT97zd2VX8EleHIMO2p6Z18b2ZxnFJGjO3PKn+JFEMlernrV/LtMh8jMPMoJD9R/AsYjFzOSELyqHauR0adoZ5r9Sb+bJikc+oWbzajsIP0qm9FNzwU6fjAZtgEpEDI2h6yd3rU2XnQicQycmc/fm7BRcMVZ7DVR6sljzvvWFNPdDwqTch46Ij6Auacnsq3ObEGGr9rkOILUwO8Xz4yL/A9cPteBWanXIFei/pKye82+LsBBgiqIcajPZgEtpQp97VY/BZAoFxV0+Uh27BohMvvIA3YX/vtVKJhU0uy+39ga9LXCp+N0+6BUNCd3qfEibMMo3+011XpFhK6HIuOk6wBil
  template:
    metadata:
      creationTimestamp: null
      name: authentik-email-credentials
      namespace: authentik
    type: Opaque
