---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-email-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgAl8d41v8hqp4yFmpL1mu9Er4Q0E1gTOuFa4S7AtZcc1DhOfgzik631K6pYurDE0kVTa5NSSCSkVFzh9QkwcXbanCMQnccG3mkhFFYpC5l4+93TmVUP2NV8wsofwa0zLsGUMmsdWdGLekgiDzRXeZQm2st2dD05D4gnLuf/yywC5rbq9kmfR0wUq5lCzyKCILnOHF+dOaTsj3vFD486oYz7iLN22CGiKfV1mLg9ybtc27gNiYTfWh6Hb9aAsNvF9tQYgcaSLRmnbS3B18pr0iKDTAVcVUIv/CgYvBvyrf8fclyawW77MH/iFvLJ6xO8wU2vR9IcStczHj11UNrJ3ZZHZFhgeknNefzeuiifWVIX9dYwpehwX6VP3sKspVJfbfHQnMD89bC2dGJxLTSF6AOwkRobJrl5duImPx5AfwIZtXv35QArIOLVscWeyxSMY+6tXgcEU99Zfvf77IjNaD9MyRohxaTKlPfL/HFmA1XMvYH3o5azDMxKB3glXToDwl1D1Ys9sC+rTHzh59zZ3ofjquwsA75lQtlMOfNSu02LbXOOGe8VYBNrwCe8kZ495XzvCxYIMHx4/lupSzBGf0W3hOBaeAJ81L6C+BvvntL1lGDoG5qpYYGNjrcqstkOFD6kU867JOCULvQFdQFXOJgLIxgQI0CpussyxhpcrxfhLN/7Qr1zDtbgx1xvkf9lsPfdUqZiEQ8+I1lUhLHCqIQ2H9VoiA==
    username: AgAZS86cdoApqF9eNcX4pf42HmV+lxIBTVA6b5627WhkO7FRlUg9JuFIW/A2b6bGnuxU4NqrAvGYufAPhb+QS8CRjBizQjgPXxFCSZncejr1nYWpG7rcDNGChBA63AFI6NVVDlhkB88lluWq7nvLggJWZb8JLQUbh+Fvs14UGGRNDL3iYoMjbwCwkyWcewMhB9Q8cpcagOLccxAnEo3AR2mGDX9mqvAHBishGJfR8Keiwc9MvJBTignqvLE3DUlpTCGnAmuKOnCcuRRdgExeu8nL/g4y7FFNM26svcMGruknFD+dKrYoHMICxFDp3Rv0XjXzmK2OP6uARYAS65zLstoHbOo8JRgH6lxMzz1p/cn5z2DFmMMTzKQo4PuyuGFHP6vHikXJLu45dH23I/z36Ya05MeFMTyjJ1dCvizGfOmmSu+No8Rc9BAICjGXfqUWgYxujp/sKtMEN3YXrdXfLj+iQZf64V7f1QyCdsHqy7A7158RLvfxfCR3HU4xrUV5AYTOTZ1LYxu2P3GYxUiYY2WBNBUc6eajoK/Kkl2yo1LI1+De6bccvGIHFU1ytByaM4+vRWDuGCWCxmhfaPtM99TWgxBU9o0eNaFi6MdCuDork01EIyOBTeVRvf5m9xjL5dvFNtW8sij8B1a7L55geJcHGuvto0uks3wEUmJg+VgcOr6Uwiqh5lTfReijaGwkCQxkm9WRZk+fh0w5CZAOR3JotV83EQ0hmwZ5gA==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-email-credentials
      namespace: authentik
    type: Opaque
