---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-email-credentials
  namespace: authentik
spec:
  refreshInterval: 12h
  secretStoreRef:
    name: onepassword-store
    kind: ClusterSecretStore
  target:
    name: authentik-email-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: email-credentials/username
    - secretKey: password
      remoteRef:
        key: email-credentials/password
