---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: authentik-redis-credentials
  namespace: authentik
spec:
  encryptedData:
    password: AgAbsR0FFSsaCYSjC0j1UX4JmHwskdrQxuAPnEnVB+Zp1vWXBMGPeGNRc5UYhdD6hieTFjDicx4za4RkEDWCQMC3aZSRBdbTxIF7zRIGKlNwoiLHyYJt9mMDTFx/yWdHvI/vkw01ZsM4LgmIEtOJtZS1zdkzuoDDeh/AMiSAm+r/l84ligDx417+gKBc6jE7vaP7YKsnGG8RiCcf4SOR8At9Y2nbg4V8PDdeU6/Dpo7I3hZDzU5yjoK5BDPZCLqTCgNjD50D5IgLATjyzzfobNDh/l5qyDdZedF1e8m68AsKPowcMxnczCxFPjryvXHXltG8uGHgOzwBp5m6Zi+b5r/rKzeiTx4r+e0zX5VqXk+HOalg2v8OBcY2eijWzAEd3qXVljN63NAflJ8bIDKkVu0Ng2AUAuiWbyXGNQ+MP3OdvWg1jd78HxSPOEEl+vQ1WDjaDkKdrsSSO6ifBpdvETdoABqEIfjx5Gh/qNV6aGq57/3jZELv6KA+0FE1hY/1gLJJubyU4V/v82TzEdEyoDO4LebchXy0oOIhC4f8LGPsXfN0g0AnIRUUDUQgsV7SvqsHDiFz862W1fAaZ228FDD+71m3XAoYY8M3Uw//a5Ve0UwPGalSVM4JxNC9i7oRkv0L9M/neImVtBJcEvDmJL+55fqL2NkE/yH8RMg4fAzVNciOcstpA5h7ljuD8b+8SxAjrHrXuj4Y5lvt8HmbUusDxd/KK1dAcC1j6N0vIMqXSg==
  template:
    metadata:
      creationTimestamp: null
      name: authentik-redis-credentials
      namespace: authentik
    type: Opaque
