---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: prometheus
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`prometheus.local.asztalos.net`)
      services:
        - name: monitoring-kube-prometheus-prometheus
          namespace: monitoring
          port: 9090
  tls:
    secretName: local-asztalos-net-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`grafana.local.asztalos.net`)
      services:
        - name: monitoring-grafana
          namespace: monitoring
          port: 80
  tls:
    secretName: local-asztalos-net-tls
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: alertmanager
  namespace: traefik
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`alertmanager.local.asztalos.net`)
      services:
        - name: monitoring-kube-prometheus-alertmanager
          namespace: monitoring
          port: 9093
  tls:
    secretName: local-asztalos-net-tls
