name: Scan Kubernetes Manifests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run KubeLinter
        uses: stackrox/kube-linter-action@v1
        with:
          directory: ./
      - name: Run Kubescape
        uses: kubescape/github-action@v2
        with:
          files: ./